### ISSUE TITLE
Prototyping: Analytics/Data ideas

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#105]
# Purpose

We use to have a strong Analytics story in the Filecoin Client ( Now Slate ). I want someone to keep the ball moving on explorations while we get Milestone 0.0.6 out the door.

![large_6272c5a3e0d75908091c0cd77b73ba10](https://user-images.githubusercontent.com/310223/88235444-bf1b7b80-cc2f-11ea-9a0a-bd43e353a8d5.png)
<img width="450" alt="large_bd7e66fa26746d886df6cd05fde894ed" src="https://user-images.githubusercontent.com/310223/88235447-bfb41200-cc2f-11ea-90a2-b8c85a7db92f.png">
![large_dea8b974190912b343dc82198a8cbf73](https://user-images.githubusercontent.com/310223/88235449-c0e53f00-cc2f-11ea-89c2-d646f619c9dc.png)

* There are awesome services like https://filscout.io/en/ that have some Data the Filecoin client should have too.
* https://www.are.na/www-jim/work-pl-01 look through this to see some prior art.

# Deliverable

* Ideas, explorations, and prototypes.

# Dependencies

* A reliable API!

**Comment by jimmylee** [comment]
https://github.com/filecoin-project/slate/issues/13 **related.**

**Comment by uonai** [comment]
@jimmylee doing a quick scrape of filscout.io, there are a few API services --

- network overview: https://filscoutv2api.ipfsunion.cn/network/overview
- message list: https://filscoutv2api.ipfsunion.cn/message/list
- global map: https://filscoutv2api.ipfsunion.cn/peer/map
- tip set: https://filscoutv2api.ipfsunion.cn/tipset/linkedList
- miner list: https://filscoutv2api.ipfsunion.cn/miner/list

Is there a plan to either (1) scrape these existing filscout APIs, (2) reference existing non-filscout APIs within our Filecoin ecosystem, or (3) build our own APIs for this type of functionality? 

As I'm browsing through the filscout endpoints, I'm not seeing any APIs that return historical transaction data. It may be that we need to index and ingest this historical data.

**Comment by jimmylee** [comment]
* We shouldn't try to scrape the API and index the data from the front-end.
* We have this tool internally https://github.com/filecoin-project/sentinel, I'd love to see if we can get a hosted version or another way to get a reliable data pipeline. cc: @placer14 or @frrist

**Comment by jimmylee** [comment]
I was wrong earlier, @placer14 directed me to: https://github.com/filecoin-project/lotus/tree/master/cmd/lotus-chainwatch where the primary function of this code is to get Lotus data into a database. We should do more research here and see who else is taking advantage of this. If its in a hosted postgres database anywhere we can make our own queries against it using our knex-front-end-tools.

**Comment by uonai** [comment]
Update: a public db is not available for consumption. Next steps, I will load a postgres db with chain data and analyze what we are working with out of the box plus identify any additional data sets that are missing but would be nice-to-have. ETA 8/2

**Comment by jimmylee** [comment]
Great!! @placer14 might be good to sync with some gotchas if you have the availability, no worries if not.
