### ISSUE TITLE
Prototyping: User Profiles

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#106]
# Purpose

<img width="1377" alt="Screen Shot 2020-07-22 at 3 45 13 PM" src="https://user-images.githubusercontent.com/310223/88236838-cdb76200-cc32-11ea-8de2-7e38d08a337b.png">

# Deliverable

* Ideas, explorations, prototypes.

# Dependencies

N/A

**Comment by harisbutt** [comment]
Synced up with @martinalong on this today. We've got solid v1 for the profiles scoped out. Going to create a new issue in the next milestone for building it out.
