### ISSUE TITLE
Picking a new brand name, domain name, and logo

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#11]
# Purpose

- We're going pick a new brand name, https://filecoin.onrender.com/logo-name-test to see the options
- We're going to buy a domain name for it
- We're going to get some help with a logo based on the most popular.

# Deliverable

- A new domain name
- A new brand
- Keep Filecoin colors.

# Dependencies

N/A

**Comment by ziyadbasheer** [comment]
May I suggest the name "Sans"? Idea is functional aesthetics vs ornamental.

**Comment by jimmylee** [comment]
Nice suggestion, I will add it to the list.

**Comment by jimmylee** [comment]
We've settled on Slate!

**Comment by jimmylee** [comment]
We have enough temporary work to satisfy this until we work with Narative. Feel free to play around regardless.
