### ISSUE TITLE
Refactor: Seeing user profiles without the `@`

### ISSUE THREAD

**Issue by pooja** [filecoin-project/slate#111]
# Purpose

Minor UX improvement request

# Deliverable

I was playing around with slate.host, and noticed that profiles are visible at, e.g. https://slate.host/@pooja, instead of having the handle directly after the slash (https://slate.host/pooja). More something to consider as opposed to a concrete feature request, but I slightly prefer the slate.host/pooja version as it's easier to type and feels more standard (e.g. GH, LinkedIn profiles do this).

**Comment by jimmylee** [comment]
I like this idea, we'll try this post 0.0.6

```
https://slate.host -> marketing page
https://slate.host/_ -> new application page
https://slate.host/username -> new profile page
https://slate.host/username/some-slug -> slate pages
https://slate.host/_/system -> new design system pages
https://slate.host/_/system/:experience
https://slate.host/_/system/:component
```
