### ISSUE TITLE
Design: Enable developer plugins in Slate

### ISSUE THREAD

**Issue by pooja** [filecoin-project/slate#115]
# Purpose

This is a feature request for Slate. :) I've been dreaming about having a way for third-party developers to build plugins in Slate and have a place where Slate users can search for plugins that they want to install into their Slate instances. This could enable all sorts of experiences/workflows that we might not want to build ourselves as a Slate team, e.g. this idea I keep talking about where we can have a Venmo-like FIL transfer through Slate (using Slate usernames maybe?).

So: I'd love to start a discussion about whether and how it would be possible to enable developers to build Slate plugins and a "plugin marketplace" that users can search through to install plugins or extensions into their Slate browser and local instances.

# Deliverable

Taking a stab:
- SDK for Slate plugins
- Submission flow for third-party devs to submit plugins
- Review process (maybe) to review third-party plugins
- Plugin marketplace exposed to users in the browser and local versions of Slate

# Dependencies

N/A

**Comment by jimmylee** [comment]
I love this idea!! I'm going to Timebox some time to brainstorm what this could look like with @harisbutt for the next milestone (0.0.8).

**Comment by jimmylee** [comment]
Punting this to the next sprint when I work on offline.
