### ISSUE TITLE
Feature: Offline Client: MacOS

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#129]
## Purpose

We want to have an offline client ready for Slate at launch.

### Architecture

Previously I made @uonai jump through some hoops to run a local server and use NextJS for builds.

* **That is no longer the case**. I have made some changes that greatly simplified the entry point for the application.

```js
import * as React from "react";

import Application from "~/components/core/Application";

export const getServerSideProps = async (context) => {
  return {
    props: { ...context.query },
  };
};

export default class ApplicationPage extends React.Component {
  render() {
    return <Application viewer={this.props.viewer} />;
  }
}
```

* A single import of `Application` means that the whole application is portable and usable in many contexts.
* We should make a new electron entry point file that populates viewer the same way (if it exists).
* **Viewer doesn't need to exist** to load the application, so the application should load the sign in screen.
* We need to modify https://github.com/filecoin-project/slate/blob/main/common/actions.js accordingly to support calls against `https://slate.host`.
* We need to also add code to use web storage instead of `cookies` in the electron context.

### Deliverable

* An electron application with a new entry point that makes HTTP calls against `https://slate.host`

### Notes

This sets the stage well for offline Slate, because with the new entry point we can add properties like:

```js
export default class ApplicationElectronContext extends React.Component {
  render() {
    return <Application isOffline localFiles={this.props.localFiles} viewer={this.props.viewer} />;
  }
}
```

Let me know if you have any questions!!

**Comment by jimmylee** [comment]
I hate to continue punting this but after I finish the Slate Page (Public) / Slate Page (Private) concept I'll be taking this task over.

**Comment by Justin2997** [comment]
@jimmylee  I can try to do this !
