### ISSUE TITLE
Adding statistics / analytics from Lotus to the client

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#13]
# Purpose

A couple of views that were taken out that would be useful to have again are the network statistics and charts.

# Deliverable

- /stats
- /data
- /peers

# Dependencies

N/A

**Comment by uonai** [comment]
@jimmylee are there any existing visual designs / wireframes for these views? I recall seeing mock ups at some point.

**Comment by jimmylee** [comment]
@uonai 

**Figma:** https://www.figma.com/file/vye9FABQeJkPAfEu2Wk3hh/Protocol-Labs-Filecoin-Node-Client-UI?node-id=0%3A1
**Figma 2:** https://www.figma.com/file/e6X0a3UXoC5p3ONjuUpMqr/https-filecoin.onrender.com?node-id=0%3A1

### Some shots

![original_4a15a41f0acbfbc83badf736e2dd594e](https://user-images.githubusercontent.com/310223/88699325-0dab9880-d0bc-11ea-93f6-b8cf00e493f1.png)
<img width="1829" alt="original_bd7e66fa26746d886df6cd05fde894ed" src="https://user-images.githubusercontent.com/310223/88699331-10a68900-d0bc-11ea-936e-5dbdad4d10ed.png">
![original_dea8b974190912b343dc82198a8cbf73](https://user-images.githubusercontent.com/310223/88699341-12704c80-d0bc-11ea-94b3-bf8d4a978e01.png)
![original_e041798b95415207d7d2aa7f684e6551](https://user-images.githubusercontent.com/310223/88699357-169c6a00-d0bc-11ea-900a-d3e7ddaef00e.png)

To reify: I wouldn't treat these as an exact prescription of how things should be. Treat these as a starting point.
