### ISSUE TITLE
Feature: Conversion tools.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#145]
# Purpose

I think it would be insanely valuable to help people convert certain data into other data types.

Examples:

+ TTF to WOFF
+ WebM to MP4
+ MP4 to GIF

# Deliverable

+ Provide a PR demonstrating the conversion from `WebM to Mp4`, we could even use a micro-service approach and start building these microservices in `GO` or `C`.
+ This will probably provide the framework for how we provide other conversions as well.
+ This may become part of the SDK story.

**Comment by gndclouds** [comment]
would also love to see:
- csv to json
- word to pdf
- pdf to image
- image to pdf

**Comment by jimmylee** [comment]
@gndclouds we should find someone who is passionate about this stuff
