### ISSUE TITLE
Switch over from react-tippy to GlobalTooltip in the client

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#170]
# Purpose

We have a new GlobalTooltip that should work in the client now 

- You can customize positioning
- The trigger for a tooltip appearing doesn't have to be a hover and doesn't have to be the same as where the tooltip appears
- Will not be cut off by overflow:hidden because it is at the root level of the document now

# Deliverable

Convert menus and tooltips that currently use react-tippy or just absolute positioning to this new GlobalTooltip

**Comment by jimmylee** [comment]
@martinalong currently we did this with the navigation menu already :) and I have already removed `react-tippy` from the codebase so you just need to find places where tooltips need to be added.
