### ISSUE TITLE
Feature: Refresh button and automatic refreshes

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#179]
# Purpose

Currently, hitting refresh in the browser resets you to the home page. Would be nice to have an in-client browser that keeps you on the same page, but just hits rehydrate.

Would also be nice for the client to refresh automatically after the user adds something to a slate, makes a new slate, etc. Right now you have to refresh in order for it to appear.

# Deliverable

- Refresh button
- Automatic refreshes where appropriate

**Comment by jimmylee** [comment]
**We address this with:**

* Websocket server
* Each client will get an update and know to update itself whenever an update occurs.

Whenever an event is fired, we simply update the viewer model and the entire app is updated.

**Comment by jimmylee** [comment]
Adding this for architecture alignment: https://github.com/filecoin-project/slate/issues/130
