### ISSUE TITLE
Add search filter tags

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#209]
# Purpose

Create a detailed set of search parameters for finding content across Slates.

![image](https://user-images.githubusercontent.com/1757261/92291141-b960c780-ef49-11ea-898a-b87831e4b705.png)

For example, Apple's finder lets you look for tags, filenames, and types.
![image](https://user-images.githubusercontent.com/1757261/92291506-959e8100-ef4b-11ea-8737-ef77998840a1.png)

# Deliverable

Some filters + scopes might include:

**File type** 
Scope - looks across all of Slate public files for a specific file type.
Input - video, text, code, ... and file extensions like .md .pdf .mov ...

**Account**
Scope - limited to files that have been shared by or commented on by users.
Input - handles and account names

**Date**
Scope - Search for a range or date a file was uploaded
Input - Newest, oldest or start YYYY-MM-DD end YYYY-MM-DD or last week, today, yesterday, etc

**Filter**
last- updated
apears-in-new-slates

# Dependencies

N/A

**Comment by jimmylee** [comment]
Awesome idea :)

**Comment by jimmylee** [comment]
@martinalong when you search sometimes, the input field locks up, so we will want to do a debounce based on some time after the user last had a keystroke.
