### ISSUE TITLE
Download file not working

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#219]
# Issue
Slate doesn't allow me to download my original file.

For image, clicking the "download file" takes me to a new tab instead. 
For video, it gives me this: 
<img width="1360" alt="Screen Shot 2020-09-06 at 11 35 48 AM" src="https://user-images.githubusercontent.com/35607644/92332816-53ea0500-f035-11ea-8c93-6c9a51d93062.png">

**Comment by jimmylee** [comment]
I resolved this by removing download file and also removing `user-select: none`.
