### ISSUE TITLE
Fix incorrect preview image from showing before refresh.

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#227]
# Purpose

When uploading a file to an existing slate the preview image is correct but when I chick into the newly image the file shown is a random file.

I saw this:
![image](https://user-images.githubusercontent.com/1757261/92424994-7bb5a600-f1b8-11ea-84f8-c487ba6619f7.png)

Should have seen this
![image](https://user-images.githubusercontent.com/1757261/92425125-e36bf100-f1b8-11ea-9703-aa3aff96368c.png)

# Deliverable

- Show the correct preview.

# Dependencies

N/A

**Comment by jimmylee** [comment]
Got it, this is what you mean by preview.

**Comment by jimmylee** [comment]
@gndclouds can you please test and let me know if this is still an issue?

**Comment by gndclouds** [comment]
Checking

**Comment by gndclouds** [comment]
I can not longer reproduce this in Safari, Chrome, or Firefox.
