### ISSUE TITLE
Chrome extension: tracking the source of images

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#231]
# Purpose
It's important to track the source of information for reasons like copyright, verifiability, etc.

# Deliverable
Automatically populate the source field when we upload an image to Slate via Chrome extension.

**Comment by jasonleyser** [comment]
thanks @tarafanlin! Yes this is on the list to do. 

@jimmylee re: about the query to send the source information, can I do this right now or is there something you need to set up first?

**Comment by jimmylee** [comment]
Its still missing. tracking in this issue: https://github.com/filecoin-project/slate/issues/203
