### ISSUE TITLE
Feature: username/password retrieval

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#234]
# Purpose

What happens when I forget about my password/user name?
How do I get my cool slates back?

# Deliverable

allow users to add phone numbers
username/password retrieval

**Comment by jimmylee** [comment]
The right thing here is to add phone numbers, we can encourage this by offering more free file storage.

**Comment by gndclouds** [comment]
Are there benefits to phone numbers over emails?

**Comment by jimmylee** [comment]
E-mail is what we're going with
