### ISSUE TITLE
Fix upload status message when data upload fails

### ISSUE THREAD

**Issue by akuokojnr** [filecoin-project/slate#235]
# Purpose
Currently, when file upload fails, the upload status displays `NaN undefined of available NaN undefined used`. See attached image below. I do not think that this looks great for the UI.
 
![sidebar-view](https://user-images.githubusercontent.com/31008944/92564243-6009d880-f268-11ea-80d8-c0e10339022b.png)

# Deliverable

A new status message when the upload fails.

# Dependencies

N/A

**Comment by jimmylee** [comment]
Thank you, I've had some reports of this as well. looking into it now :)
