### ISSUE TITLE
Handling for user or slate deletion

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#240]
# Purpose

Encountered an issue where I wasn't able to log into my account (client threw an error), likely because someone I followed or a slate I followed had been deleted. As a result, it showed up as undefined and errored.

# Deliverable

We need the database to properly clear deleted users and slates or for the endpoints to handle them without returning an undefined.

**Comment by jimmylee** [comment]
@martinalong is working on this.

**Comment by jimmylee** [comment]
Seems like this has been resolved.
