### ISSUE TITLE
Organize Slate Assets

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#251]
# Purpose

Creating a list of all assets so that @cake can show @tara and @gndclouds how to best import them.

# Deliverable

List of assets.

# Dependencies

All images are included and listed in the order they appear:

## Marketing
**Hero Image:** https://bafkreif4bmrb6m3akzq76chhz55q4iirjrcy7lmhlvj2qneczgubujafmi.ipfs.slate.textile.io/
**Hero Video:** https://bafybeidfr2x5ftxzixjxtrgiqm6iuotzip25tlrpase226jog3tqenqd4a.ipfs.slate.textile.io/

**Example video Image:** 
https://bafybeidnt2l3lslxi7ofkxs5ffncsh4fw5h2ohbukxumngrqj5pdrooaou.ipfs.slate.textile.io/
**Example video Video:** https://bafybeidfqsrz66ytrvb3s5t2o2rywppgbwyd6dzs4rbjwugder6kfly7wm.ipfs.slate.textile.io/

**Example PDF image:** https://bafkreihu7k46n6eixx6sxjv7aolou5bgvksvb7ryju3gbwie22t6r2dhli.ipfs.slate.textile.io/
**Example PDF video:** https://bafybeihxwfapkfcp6s5t4tty2fhxwuu6zhicaq2lvfmmgqrqifwpdpyoda.ipfs.slate.textile.io/

**Example Audio image:** https://bafkreibb3onijljnmonrbs7qguimjf5qwbnkx3m33pouxbtar2yb7hupti.ipfs.slate.textile.io/ 
**Example Audio video:** https://bafkreid7wl4443p764ozdlqtodh7dmsej6ffayp4tc3lr3hil2qkclrohi.ipfs.slate.textile.io/

**Example slides image:** https://bafybeidnt2l3lslxi7ofkxs5ffncsh4fw5h2ohbukxumngrqj5pdrooaou.ipfs.slate.textile.io/
**Example slides video:**
https://bafybeifl5xzy4vjctrsr3jywdlv5ceq3hpaadhcii2ekjx2gljyagveqna.ipfs.slate.textile.io/

**Chrome extension Image:** https://bafybeig46uuyp3fkjpk2edeqlmt26r3rxdola52dy7kbgvjms6olyucjdu.ipfs.slate.textile.io/
**Chrome extension Video:**  N/A

**Create Moodboard Image:**https://bafybeicoaponp2nv3ikpsjgcgu7pio6aercflsvsiyxrpaonza7ncg73dq.ipfs.slate.textile.io/
**Create Moodboard Video:**  https://bafybeiagnzwfvdsqqxamlpru2fulmwzlgaqtg4ys4gs4wfnm5rq75c2cs4.ipfs.slate.textile.io/

**Organize research Image:** @tara where is this asset?
**Organize research Video:** https://bafybeiebuwbxcvjhvop2qeuu2zc75kclybr56flnn6bnwzznsokgqc43da.ipfs.slate.textile.io/

**Share Presentation Image:** https://bafkreiglefskwq7bpa3aazihegawd4qwxockl6shipnps7zlokrbnu4f7u.ipfs.slate.textile.io/
**Share Presentation Video:** https://bafybeiampkmsxeihxnuz2hkgbhtzosgkwghslpwm7dsrxrzlqwa7tvzreq.ipfs.slate.textile.io/

Slate Previews
**Garden:**

**Brand:** https://bafybeiaerbu2nivrgncqtwgwom27caji25netswvjbo6tcmbka47ucmupa.ipfs.slate.textile.io/https://bafybeiaerbu2nivrgncqtwgwom27caji25netswvjbo6tcmbka47ucmupa.ipfs.slate.textile.io/
**Books:** https://bafkreihe7ismqfyytekj6yvbv6mpbc5de3gozk6n7a47smodbcsnrhbpri.ipfs.slate.textile.io/
**underground:** https://bafybeieblkyt6d7wg4xmltshvxm6w7tz4c3zjpjuu4yfhiak36debqccda.ipfs.slate.textile.io/
**papers:** https://bafkreif7l2vxkvdyrydcjwjjrrmqq73id3tdrdkf3z54tp2fotc75wkdwm.ipfs.slate.textile.io/
**mountains:**https://bafkreies6uykgocrkunrsndxfubntyqvfqzo5wuwyos42vak6d4qnvtdn4.ipfs.slate.textile.io/
**Monet:** https://bafkreieb4yfiamtipapmhoihl547lxeod2vfku67dimrhmab5tcglr5bli.ipfs.slate.textile.io/
**Loom:** (@gndclouds needs to be compressed )https://bafybeidh756q35itrotpdwhjz3d5kwzac3brqy43mmwenq2iqaorbjssem.ipfs.slate.textile.io/
**Shapes:** https://bafybeifgxtl7mq5djnorxedzi35hkizjmbjvdy3nnoitd3xvdnqpmruxbm.ipfs.slate.textile.io/

---------------------------
## Contributors

Hero Cube Image: N/A
Hero Cube Video: https://bafybeigtl3tjyozxxkabdvfdhopkep62ux4grgritlslwusgww6gdmm5da.ipfs.slate.textile.io/

Team Card :hover https://bafybeieivxv7qriuwamfz24wvwy4eiim6behhmewpplnhvhdm3gmbfdeci.ipfs.slate.textile.io/

---------------------------

**Comment by jimmylee** [comment]
Thanks for doing this! Hopefully we can test these out against what is here: https://github.com/filecoin-project/slate/blob/main/pages/index.js
