### ISSUE TITLE
Design: Save button status indicator

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#252]
# Purpose
When I click on the Save button for my new edits in this window, I hope there could be some visual indicator to show that I've successfully saved my edits. 

<img width="1440" alt="Screen Shot 2020-09-11 at 11 47 43 AM" src="https://user-images.githubusercontent.com/35607644/92961739-a015ba80-f424-11ea-9c31-2ec55ab889ca.png">

# Deliverable
## Solution 1
A checkmark indicating I've successfully saved the current edits
## Solution 2
Auto-save? Not sure if this is desirable over the manual save

**Comment by jimmylee** [comment]
Would be useful to have a timestamp as well.

**Comment by jimmylee** [comment]
Still needs an exploration
