### ISSUE TITLE
We need CSS fallback for Safari cases

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#253]
# Purpose
We cannot see the input field on the login page. 
It's there, we just can't see it.

<img width="1440" alt="Screen Shot 2020-09-11 at 11 41 26 AM" src="https://user-images.githubusercontent.com/35607644/92962098-4792ed00-f425-11ea-98b0-73330f247f0b.png">

# Deliverable
We need CSS fallback for Safari cases

**Comment by jimmylee** [comment]
<img width="1800" alt="Screen Shot 2020-09-12 at 8 41 48 PM" src="https://user-images.githubusercontent.com/310223/93009651-66ce6f00-f538-11ea-80e7-dc8179afca09.png">

@martinalong looking good
