### ISSUE TITLE
Uploading files to a Slate doesn't always work even when uploads are finished

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#255]
# Purpose
When I upload a large chunk of data to a slate, it doesn't always get put into slate even all the uploads are completed. Not sure why it happens.
Currently, I will go to each data file and manually save the file to the Slate. 
But I hope it could behave more consistently in the near future.

# Deliverable
More stable performance for uploading data to a slate.

**Comment by jimmylee** [comment]
@tarafanlin can you test again this with the latest build? We may have made some improvements here.

**Comment by tarafanlin** [comment]
Just tried and it seems to work fine. So closing this issue.
