### ISSUE TITLE
Marketing v1 Todos

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#261]
# Purpose

Lists of Todos from @tarafanlin and @gndclouds for Marketing v1 Launch.

# Deliverable

Site-Wide:

- [ ] Check All Copy again
- [x] Check all links and paths
- [ ] Check all Videos and Preview Assets (on hold pending cake extension findings)

Landing Page:
- [ ] Fix Videos mov /mp4 issues in safari (on hold pending cake extension findings)
- [x] Make mobile Padding Styling make fill width

Community Page
- [x] Style Github Issues
- [x] Fix Leading Bug for Terminal interface
- [x] Reduce for Design System and API

Download Page
- [ ] Replace static image with Video of how Plugin Works
- [x] Remake Table Element

# Dependencies

N/A

**Comment by tarafanlin** [comment]
- [ ] add font weight
- [ ] adjust padding for different browsers
