### ISSUE TITLE
Marketing Site v2 - Things to take further

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#262]
# Purpose

While reviewing @tarafanlin and @gndclouds started list of possible improvements for v2 of the marketing page.

# Deliverable

**File Preview**
Moved to Issue #283 

- Links or external references (this is shortlisted as a conversation to revisit as we think about growing based on the roadmap)
    - Vimeo
    - YouTube
    - Figma 

**Chrome extension** 
- Auto capture metadata
 - Save text associated with images 
- Detect what you might be trying to capture 
- Save and Edit metadata of file before saving to slate

**Commenting**
- Ability to comment 
- Highlighting 

Versioning control
- Show past version of a file

# Dependencies

N/A

**Comment by tarafanlin** [comment]
- [ ] remove npm
