### ISSUE TITLE
Design: different affordances on file interface under data vs. slate page

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#265]
# Purpose
Not sure why the interface for the same data file is different when it's under **data** vs. **slate**
Is there a way for us to combine the affordances and make it the same across all pages? 

<img width="1440" alt="Screen Shot 2020-09-12 at 12 36 26 PM" src="https://user-images.githubusercontent.com/35607644/93003593-dde21400-f4f4-11ea-9b98-5ff8ff27bee3.png">
<img width="1440" alt="Screen Shot 2020-09-12 at 12 37 04 PM" src="https://user-images.githubusercontent.com/35607644/93003595-e33f5e80-f4f4-11ea-84b2-0318ddf7901e.png">

**Comment by jimmylee** [comment]
This is an important design discussion:

**Data Item**: Your root level CID, and how it is used across multiple Slates.
**Slate Item**: The reference to the CID, and how it can be used elsewhere.

**Comment by tarafanlin** [comment]
I see. 
Follow up on that: why can't we still provide the same affordances regardless of whether or not it's a reference or the root CID?

**Comment by tarafanlin** [comment]
Oh I just realized that if you add the data item to a different slate, the description I have in one slate will be gone..
Huh this is something we should probably discuss as a team. It might be a little confusing to people.

**Comment by jimmylee** [comment]
I'll try something now and see what you think.

**Comment by jimmylee** [comment]
I'm closing this issue because we addressed a portion of it, and we will need a feature design for the next evolution of it.
