### ISSUE TITLE
Design: configure visibility when creating slate?

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#267]
# Purpose

Should we allow users to configure the visibility of slate when they create it? 
I think private slates might be a common user choice. 
<img width="416" alt="Screen Shot 2020-09-12 at 5 17 13 PM" src="https://user-images.githubusercontent.com/35607644/93007297-3ed11280-f51c-11ea-9ecb-cc7c820d3cb3.png">

**Comment by martinalong** [comment]
Good call! I'll add that to the to-do list

**Comment by tarafanlin** [comment]
adding a note that description input is also nice to have :] 

<img width="402" alt="Screen Shot 2020-09-12 at 5 36 25 PM" src="https://user-images.githubusercontent.com/35607644/93007529-9e302200-f51e-11ea-84b5-a138c55d378f.png">
