### ISSUE TITLE
Documentation: docs.filecoin.io

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#27]
# Purpose

+ Stakeholders of Filecoin want to see tutorials on https://docs.filecoin.io

# Deliverable

+ Tutorial to live in https://docs.filecoin.io

**Comment by jimmylee** [comment]
SDS responsibilities: Components, Experiences
docs.filecoin.io responsibilities: How to use components, experiences to make an application.

<img width="1482" alt="left-content" src="https://user-images.githubusercontent.com/310223/86217174-f072c100-bb33-11ea-8d40-8f54272402c5.png">

**Comment by jimmylee** [comment]
# How to build a Filecoin application using Slate React System and Textile's Powergate. (MacOS)

This tutorial is a step by step guide for how to build your own Filecoin application using Textile's Powergate and Slate's React Component Library. In this tutorial you will learn how to

- Set up your environment
- Run your starting point
- Import Slate React Components
- Integrate Powergate
- Create a Powergate authentication token
- Create a new Filecoin address
- Send funds between Filecoin Addresses

There tutorial also involves a rendering library named `React` and a framework for building React applications called `NextJS`. For styling we use a stylind library named `Emotion` and for transpiling JavaScript we use `Babel`.

## Set up your environment

To do this example, you're going to need to install `node` and `go`. One of the easiest ways to do this is to install `brew` and `xcode-select`.

Once you have [homebrew](https://brew.sh/) installed, you can follow the rest of these steps:

First check if MacOS XCode Command Line Tools are installed:

```
xcode-select -p
```

If there is no response, then install them using this command:

```
xcode-select --install
```

Then install both `node` and `go`

```sh
brew install node.
brew install go.
```

Now you can start your project.

Find a directory on your computer. Create a directory called `my-powergate-project`

```sh
mkdir my-powergate-project
```

Afterwards create a file called `package.json` and `.babelrc`.

```sh
cd my-powergate-project
touch package.json
touch .babelrc
```

You will need to add contents, just copy and paste the following below:

#### /package.json

```sh
{
  "name": "my-powergate-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@emotion/core": "^10.0.28",
    "@emotion/cache": "11.0.0-next.12",
    "@emotion/css": "11.0.0-next.12",
    "@emotion/react": "11.0.0-next.12",
    "@emotion/server": "11.0.0-next.12",
    "@emotion/styled": "11.0.0-next.12",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "next": "latest",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "@textile/powergate-client": "0.1.0-beta.13",
    "slate-react-system": "0.0.4"
  }
}

```

#### /.babelrc

```sh
{
  "presets": [
    [
      "next/babel",
      {
        "transform-runtime": {
          "useESModules": false
        }
      }
    ],
    "@emotion/babel-preset-css-prop"
  ]
}
```

- As this tutorial ages, we may not need some of these dependencies in the future.
- It may feel like a lot, but this is everything we will ever need to do the full tutorial.

Now run `npm install`. After it has completed. Do the following:

```sh
mkdir pages
cd pages
touch index.js
touch _app.js
touch _document.js
```

Then populate the files with the following

#### /pages/_document.js

```js
import Document, { Head, Main, NextScript } from "next/document";
import { extractCritical } from "@emotion/server";

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    const styles = extractCritical(initialProps.html);
    return {
      ...initialProps,
      styles: (
        <>
          {initialProps.styles}
          <style
            data-emotion-css={styles.ids.join(" ")}
            dangerouslySetInnerHTML={{ __html: styles.css }}
          />
        </>
      ),
    };
  }

  render() {
    return (
      <html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

#### /pages/_app.js

```js
import { CacheProvider } from "@emotion/react";
import { cache } from "@emotion/css";

function MyApp({ Component, pageProps }) {
  return (
    <CacheProvider value={cache}>
      <Component {...pageProps} />
    </CacheProvider>
  );
}

export default MyApp;
```

In your index.js

```js
import * as React from "react";

import { css } from "@emotion/react";

const STYLES_PAGE = css`
  margin: 0;
  padding: 0;
`;

export default class TestPage extends React.Component {
  render() {
    return <div css={STYLES_PAGE}>Hey everyone!</div>;
  }
}
```

## Run your starting point

In terminal, run the following:

```sh
next
```

You should see the the following in your browser at `localhost: 3000`:

<img width="842" alt="Screen Shot 2020-07-14 at 7 05 00 PM" src="https://user-images.githubusercontent.com/310223/87494960-240a1c80-c605-11ea-9f1b-70262918781b.png">

## Import Slate React Components

In `/pages/index.js` add the following line underneathe

```js
import * as React from "react";
import * as System from "slate-react-system";
```

Then you can start using `slate-react-system` components. A list of design system components live here: [https://slate.host/system](https://slate.host/system).


Here is an example of geting a button to appear:

```js
import * as React from "react";
import * as System from "slate-react-system";

import { css } from "@emotion/react";

const STYLES_PAGE = css`
  margin: 0;
  padding: 0;
`;

export default class TestPage extends React.Component {
  _handleClick = () => alert('You clicked me!');

  render() {
    return (
      <div css={STYLES_PAGE}>
        <System.ButtonPrimary onClick={this._handleClick}>
          Hello There
        </System.ButtonPrimary>
      </div>
    );
  }
}

```

<img width="967" alt="Screen Shot 2020-07-14 at 7 07 10 PM" src="https://user-images.githubusercontent.com/310223/87495012-3c7a3700-c605-11ea-815b-7b1eeb48c01d.png">

* ...

## Integrate Powergate

Now that you have a web sever running, its time to run Powergate on your machine. You will need to do the following:

```sh
git clone https://github.com/textileio/powergate.git
cd powergate
cd docker
make localnet
```

Once you have power gate running, you can add this code to `/pages/index.js`

```js
// createPow({ host: "http://0.0.0.0:6002" });
import { createPow } from "@textile/powergate-client";

```

## Create a Powergate authentication token

Now that you have Powergate setup, lets add a component from the design system and create Powergate token.

```js
import * as React from "react";
import * as System from "slate-react-system";

import { css } from "@emotion/react";
import { createPow } from "@textile/powergate-client";

const STYLES_PAGE = css`
  margin: 0;
  padding: 0;
`;

export default class TestPage extends React.Component {
  PG = null;
  state = { token: null };

  _handleCreateToken = async () => {
    this.PG = createPow({ host: "http://0.0.0.0:6002" });

    const FFS = await this.PG.ffs.create();

    this.setState({ token: FFS.token ? FFS.token : null });

    this.PG.setToken(FFS.token);
  };

  render() {
    return (
      <div css={STYLES_PAGE}>
        <System.CreateToken onClick={this._handleCreateToken}>
          Hello There
        </System.CreateToken>
      </div>
    );
  }
}
```

It also helps to add a refresh button:

```js
import * as React from "react";
import * as System from "slate-react-system";

import { css } from "@emotion/react";
import { createPow } from "@textile/powergate-client";

const STYLES_PAGE = css`
  margin: 0;
  padding: 0;
`;

export default class TestPage extends React.Component {
  PG = null;
  state = { token : null, info: null, addrsList: [] };

  _handleCreateToken = async () => {
    this.PG = createPow({ host: "http://0.0.0.0:6002" });

    const FFS = await this.PG.ffs.create();

    this.setState({ token: FFS.token ? FFS.token : null });

    this.PG.setToken(FFS.token);
  };

  _handleRefresh = async () => {
    const { addrsList } = await this.PG.ffs.addrs();
    const { info } = await this.PG.ffs.info();
    this.setState({ addrsList, info });
  }

  render() {
    return (
      <div css={STYLES_PAGE}>
        <System.CreateToken onClick={this._handleCreateToken}>
          Hello There
        </System.CreateToken>
        <System.ButtonPrimary onClick={this._handleRefresh}>
          Refresh
        </System.ButtonPrimary>
      </div>
    );
  }
}
```

<img width="967" alt="Screen Shot 2020-07-14 at 7 08 14 PM" src="https://user-images.githubusercontent.com/310223/87495118-70555c80-c605-11ea-8e7f-fea0928f2518.png">

* ...

From this point, we should also add a way to see the wallet we get for free.

```js
import * as React from "react";
import * as System from "slate-react-system";

import { css } from "@emotion/react";
import { createPow } from "@textile/powergate-client";

const STYLES_PAGE = css`
  margin: 0;
  padding: 0;
`;

export default class TestPage extends React.Component {
  PG = null;
  state = { token : null, info: null, addrsList: [] };

  _handleCreateToken = async () => {
    this.PG = createPow({ host: "http://0.0.0.0:6002" });

    const FFS = await this.PG.ffs.create();

    this.setState({ token: FFS.token ? FFS.token : null });

    this.PG.setToken(FFS.token);
  };

  _handleRefresh = async () => {
    const { addrsList } = await this.PG.ffs.addrs();
    const { info } = await this.PG.ffs.info();
    this.setState({ addrsList, info });
  }

  render() {
    const { token, info } = this.state;

    return (
      <div css={STYLES_PAGE}>
        <System.CreateToken onClick={this._handleCreateToken}>
          Hello There
        </System.CreateToken>

        <System.ButtonPrimary onClick={this._handleRefresh}>
          Refresh
        </System.ButtonPrimary>

        {info ? (
          <System.FilecoinBalancesList data={info.balancesList} />
        ) : null}
      </div>
    );
  }
}
```

Now you can add other things...

## Create a new Filecoin address

Create a class member function for the create address handler.

```js
_handleCreateAddress = async ({ name, type, makeDefault }) => {
  const response = await this.PG.ffs.newAddr(name, type, makeDefault);
}
```

Add the component to the return value of `render()`

```js
<System.CreateFilecoinAddress onSubmit={this._handleCreateAddress} />
```

Now when you hit **Refresh** you should see a new address after you use the component.

## Send funds between Filecoin Addresses

Create a class member function for the send filecoin address handler.

```js
_handleSendFilecoin = async ({ source, target, amount }) => {
  const response = await this.PG.ffs.sendFil(source, target, amount);
}
```

Add the component to the return value of `render()`

```js
<System.SendAddressFilecoin onSubmit={this._handleSendFilecoin} />
````

Now when you hit **Refresh** you should see the balances have been updated for Filecoin you are sending between addresses.

## Complete example

Here is a complete snippet for your `/pages/index.js` if you followed all the steps.

```js
import * as React from "react";
import * as System from "slate-react-system";

import { css } from "@emotion/react";
import { createPow } from "@textile/powergate-client";

const STYLES_PAGE = css`
  margin: 0;
  padding: 0;
`;

export default class TestPage extends React.Component {
  PG = null;
  state = { token : null, info: null, addrsList: [] };

  _handleCreateToken = async () => {
    this.PG = createPow({ host: "http://0.0.0.0:6002" });

    const FFS = await this.PG.ffs.create();

    this.setState({ token: FFS.token ? FFS.token : null });

    this.PG.setToken(FFS.token);
  };

  _handleCreateAddress = async ({ name, type, makeDefault }) => {
    const response = await this.PG.ffs.newAddr(name, type, makeDefault);
  }

  _handleSendFilecoin = async ({ source, target, amount }) => {
    const response = await this.PG.ffs.sendFil(source, target, amount);
  }

  _handleRefresh = async () => {
    const { addrsList } = await this.PG.ffs.addrs();
    const { info } = await this.PG.ffs.info();
    this.setState({ addrsList, info });
  }

  render() {
    const { token, info } = this.state;

    return (
      <div css={STYLES_PAGE}>
        <System.CreateToken onClick={this._handleCreateToken}>
          Hello There
        </System.CreateToken>

        <System.ButtonPrimary onClick={this._handleRefresh}>
          Refresh
        </System.ButtonPrimary>

        {info ? (
          <System.FilecoinBalancesList data={info.balancesList} />
        ) : null}

        {info ? (
          <System.CreateFilecoinAddress onSubmit={this._handleCreateAddress} /> 
        ) : null}

        {info ? (
          <System.SendAddressFilecoin onSubmit={this._handleSendFilecoin} /> 
        ) : null}
      </div>
    );
  }
}
```

That should get your started!

* For more components, check out https://slate.host/system
* To see more of whats possible, check out Powergate!

Thank you!

**Comment by pooja** [comment]
This is awesome @jimmylee ! I think looks good to push it up -- want to do a quick check-in on structure for the docs site?

**Comment by jimmylee** [comment]
https://github.com/filecoin-project/filecoin-docs/pull/158
