### ISSUE TITLE
Bug: Chrome Extension full screen mode

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#272]
# Purpose

If the browser is in full-screen mode the extension also opens in full-screen mode. It would be nice if it hovered more like a dropdown menu.

# Deliverable
Current version
![Untitled 2020-09-13 16_01_43](https://user-images.githubusercontent.com/1757261/93013363-7605f900-f5da-11ea-80c6-8205771cb397.gif)

Suggested Version - Move the clipper to a small toast like this example of the toast plugin.
![image](https://user-images.githubusercontent.com/1757261/93013375-874f0580-f5da-11ea-8d00-52bf7207021f.png)

*Tell us about what the outcome of resolving this issue will be*

# Dependencies

N/A

**Comment by jimmylee** [comment]
@jasonleyser this is in your ballcourt!

**Comment by jimmylee** [comment]
Still in your ballcourt
