### ISSUE TITLE
Bug: Uploading files from slate fails to save them to that slate.

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#273]
# Purpose

When in adding new files from within a slate the files upload but do not save to the slate. (Tested in firefox, chrome, and safari). But the files do upload and show up in the data folder.

# Deliverable

Files uploaded into a slate should be saved to that slate.

# Dependencies

N/A

**Comment by jimmylee** [comment]
I just tested this on https://slate.host

* drag and drop
* + icon

Both work?

**Comment by gndclouds** [comment]
After clearing the browser cache this resolved its self.

**Comment by gndclouds** [comment]
New info: When uploading one file at a time this seems to happen but not when uploading multiple image from safari

**Comment by gndclouds** [comment]
This is frustrating, Just closed and reopened safari and now it works again. 🤷🏻‍♂️ Maybe we can leave this open this week and I will try to track this down.

**Comment by martinalong** [comment]
Hey @gndclouds is this still an issue for you? I think I fixed some things a week or two ago that may have been causing this, but if you're still experiencing this problem let me know.

**Comment by gndclouds** [comment]
Yes but only on accounts which are also having general upload issues like mine. So it may be linked to that
