### ISSUE TITLE
Feature: Add ability to order and sort slates

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#274]
# Purpose

In the Slate App, it would be nice to be able to change the order of slates displayed on my profile and sort slate alphabetically in the side panel.

![image](https://user-images.githubusercontent.com/1757261/93040433-97b7bc80-f67c-11ea-8451-2f419e88246b.png)

# Deliverable

- Sort Slate in dashboard alphabetically
- Ability to change order slates are displayed on the profile for example slate.host/gndclouds

# Dependencies

N/A

**Comment by jimmylee** [comment]
Which do you want, alphabetical, or the order in which they are created?

**Comment by gndclouds** [comment]
For the dropdown shown in the image, I think alphabetically would make more sense. By for my profile slate.host/gndclouds/slate I would want the most recent first
