### ISSUE TITLE
Feature: PDF file previews

### ISSUE THREAD

**Issue by jacobwaites** [filecoin-project/slate#277]
# Purpose

PDF files feel disjointed in this visual layout when placed alongside other files with thumbnails!

# Deliverable

Creating dynamic cover thumbnails for pdfs, or allowing for upload of thumbnails for PDF files or files that can't support thumbnails.

**Comment by jimmylee** [comment]
Thank you so much for filing this, we'll need to do some explorations to get this right.

**Comment by gndclouds** [comment]
Added to #283
