### ISSUE TITLE
Bug: Uploading a new file to a slate resets the layout of the slate

### ISSUE THREAD

**Issue by jacobwaites** [filecoin-project/slate#279]
# Purpose

Created multiple advanced layouts and then they were destroyed when I added or deleted a file from the slate, I don't know if this is a feature or a bug, but it is annoying if you've created a complex wonky grid and then have to recreate it every time you delete a file or add a file.

# Deliverable

Maybe just add new files to the bottom of the stack and reflow items naturally after a file is removed?

**Comment by jimmylee** [comment]
This is definitely a bug we need to fix :) Thank you for bringing it up !!

**Comment by jimmylee** [comment]
@martinalong killed it again!
