### ISSUE TITLE
Feature: Delete multiple CIDs at once to free up space

### ISSUE THREAD

**Issue by jacobwaites** [filecoin-project/slate#280]
# Purpose

Uploaded a ton of files an almost hit my data cap, unfortunately, they don't have thumbnails, so I was going to reformat to make things prettier. Then found that I would have to delete each CID manually from my data list to reclaim my storage space.

# Deliverable

Would it be possible to add select checkboxes for bulk operations on CIDs?

**Comment by tarafanlin** [comment]
These are so helpful to learn. Thanks for filing the issues to help us prioritize near term design decisions! @jacobwaites

**Comment by jimmylee** [comment]
Thank you @jacobwaites !!

**Comment by martinalong** [comment]
Yup I'll get on that! 

Re: thumbnails, not sure when you tried this but recently we added a new data view where you can toggle between thumbnails and list (up in the right hand corner of this screenshot). Hearing what you and others are saying, I think I'll probably make thumbnails the default
![image](https://user-images.githubusercontent.com/33686587/93126771-a94f9300-f681-11ea-9319-9d84bbbbb242.png)

**Comment by jacobwaites** [comment]
@martinalong Ah when I said thumbnails before I meant image previews (I made a separate feature request asking about PDFs having dynamic thumbnails as a possibility), I was going to re-upload as jpegs instead to be more visual! Totally did see the switcher though, I agree that it might be a good default! I feel like I could see bulk actions being able to be applied to either view.

**Comment by martinalong** [comment]
Hey @jacobwaites ! Just an update here. We added multi delete to the list view (coming soon to grid view once we have a design for that). It's been pushed to development, but if you're using the production version on slate.host, it may be a bit before this change is pushed there.

Though I think the data limit has recently been upped to 50GB so hopefully you have enough storage space now and don't have to delete files to save space!

As for pdf thumbnails, I completely agree. Getting video and pdf previews is definitely on our to-do list

**Comment by tarafanlin** [comment]
@martinalong Just tested the multi delete on Filecoin.onrender. I wonder if we could put the delete button at top/or somewhere prominent? When I click on the checkbox I didn't know where to perform delete until I scroll to the bottom.
