### ISSUE TITLE
Bug: Account Settings bio boarder 

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#282]
# Purpose

Under **Account settings**, the Bio section does not have a border

![image](https://user-images.githubusercontent.com/1757261/93171349-80033580-f75b-11ea-833c-c6ddeb84a401.png)

# Deliverable

Bio text area should have a border which matches username text area

# Dependencies

N/A

**Comment by jimmylee** [comment]
Thank you @charlesvinette for jumping on this and @gndclouds for reporting!
