### ISSUE TITLE
Feature: Supported file types and previews 

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#283]
# Purpose

A collection of all the requested file types and previews for slate. In an effort to track these types please use the following key:
 [ Data Type: Value ] - Weather or not Slate will accept the file type
 [ Preview: Value ] - Weather or not Slate will show a non-icon based preview

Value can be: Supported, Requested, or N/A (not Tested yet by @gndclouds)

# Deliverable

**Image Files:**
- [x] .png [ Data Type : Supported ] [ Preview : Supported ]
- [x] .jpg [ Data Type : Supported ] [ Preview : Supported ]
- [ ] .heif [ Data Type : Supported ] [ Preview : Requested ]
- [x] .gif [ Data Type : Supported ] [ Preview : Supported ]
- [ ] .pdf [ Data Type : Supported ] [ Preview : Requested ]
- [ ] .webp [ Data Type : N/A ] [ Preview : N/A ]

**Video Files:**
- [ ] .mov [ Data Type : Supported ] [ Preview : Requested ]
- [ ] .ogg [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .mp4 [ Data Type : Supported ] [ Preview : Requested ]
- [ ] .wav [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .hevc [ Data Type : N/A ] [ Preview : N/A ]

**Text Files:**
- [ ] .csv [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .excel [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .numbers [ Data Type : N/A ] [ Preview : N/A ]

- [ ] .md [ Data Type : Supported ] [ Preview : Requested ]
- [ ] .txt [ Data Type : Supported ] [ Preview : Requested ]
- [ ] .odt [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .doc [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .docx [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .pages [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .xml [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .numbers [ Data Type : Supported ] [ Preview : N/A ]

- [ ] .json [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .css [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .js [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .py [ Data Type : Supported ] [ Preview : N/A ]
- [ ] .html [ Data Type : Supported ] [ Preview : N/A ]

- [ ] .pdf [ Data Type : Supported ] [ Preview : Requested ]
- [ ] .opf [ Data Type : N/A ] [ Preview : N/A ]
- [ ] .epub [ Data Type : Supported ] [ Preview : Requested ]

- [ ] OTF [ Data Type : Supported ] [ Preview : Requested ]
- [ ] TTF [ Data Type : Supported ] [ Preview : Requested ]
- [ ] WOFF [ Data Type : Supported ] [ Preview : Requested ]

**Creative Tools:**
-  [ ]  .obj [ Data Type : N/A ] [ Preview : N/A ]
-  [ ]  .stl [ Data Type : Supported ] [ Preview : Requested ]
-  [ ]  .ai [ Data Type : N/A ] [ Preview : N/A ]
-  [ ] .psd [ Data Type : N/A ] [ Preview : N/A ]
-  [ ]  .indd [ Data Type : N/A ] [ Preview : N/A ]

**Bundles:**
-  [ ]  Unity Games [ Data Type : Requested ] [ Preview : Requested ]
-  [ ]  .rom [ Data Type : Supported ] [ Preview : N/A ]

# Dependencies

N/A

**Comment by raulk** [comment]
Can we add webp as well?

**Comment by gndclouds** [comment]
@raulk thanks for the suggestion its been added!

**Comment by tarafanlin** [comment]
**maybe all the creative cloud file type as well**

- [ ] .ai
- [ ] .psd
- [ ] .psd
- [ ] .psd

**Comment by tarafanlin** [comment]
**Font type**

- [ ] OTF
- [ ] TTF
- [ ] WOFF

**Comment by tarafanlin** [comment]
- [ ] .pages

**Comment by gndclouds** [comment]
Thanks @tarafanlin they have been added!

**Comment by tarafanlin** [comment]
> Thanks @tarafanlin they have been added!

this is an awesome and ambitious issue
