### ISSUE TITLE
Feature: Add markdown support to user bios and Slate description 

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#284]
# Purpose

So increase personalization and customization of user profiles and Slates.

# Deliverable

User Bio and Slate descriptions would support markdown https://daringfireball.net/projects/markdown/

# Dependencies

N/A

**Comment by jimmylee** [comment]
@charlesvinette I know you're helping with this one ^.^

**Comment by charlesvinette** [comment]
Perfecto! When I'm done with #165 I'll make sure it renders for Bios as well
