### ISSUE TITLE
Design: building different type of Slate structure beyond gallery view

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#285]
# Purpose
We could enable people to experiment with ways of organizing and sharing information by choosing different types of slates.
To quote Haris: it's an AR of our brain. 
There are many ways in which we could structure digital gardens. 

# Deliverable
## A linear thread slate that allows commenting, file dropping for a topic.
<img width="1440" alt="Screen Shot 2020-09-15 at 11 30 59 AM" src="https://user-images.githubusercontent.com/35607644/93249957-f184b900-f746-11ea-8f14-cdac407e6f22.png">

## A node-link diagram slate
<img width="1440" alt="Screen Shot 2020-09-15 at 11 30 22 AM" src="https://user-images.githubusercontent.com/35607644/93250009-03665c00-f747-11ea-8057-6c3cb648fe3c.png">

## A slate that allows you to map ideas to places
![ylrn2BnOR1-2bDD1-RVQwQ](https://user-images.githubusercontent.com/35607644/93250412-a5864400-f747-11ea-8f45-f34af3f6de62.jpg)

**Comment by gndclouds** [comment]
I have been wanting to explore views for weeks 😅 as I think it could be a very compelling augmentation on how we conceptualize file directories. Literally every other storage system is just a directory view most of the time. 🙄

So I have lots of thoughts. First I think the current gallery view feels like a great default and I think the one quick variation on it could be to have a more canvas like view kinda like Kinopio.

## Canvas View
![image](https://user-images.githubusercontent.com/1757261/93482780-a8915800-f932-11ea-94bb-5f0b0741f029.png)

Perhaps you could visualize connections to other Slates which are Deep-linked as well as just have another way to spacially organize things.

## Static SItes.
I was a heavy user of [Small Victories](https://www.smallvictori.es) which basically uses your dropbox to host static site files based on a few templates. I see an option in which we if a user uploads a slate.config file they can pick a theme or link to a custom CSS theme. Some cool templates might be, a blog, presentation, portfolio, gallery, feed, storefront, etc. The SV site is very simple as you can see [here](https://demo.smallvictori.es/campaign-theme)
![image](https://user-images.githubusercontent.com/1757261/93483773-bdbab680-f933-11ea-8cd9-0a98d745d043.png)

Also, Jacob mentioned this too on the product hunt page.
![image](https://user-images.githubusercontent.com/1757261/93485024-2eae9e00-f935-11ea-8ef6-3e3911d391c6.png)

## Storefront
I have a lot of friends who sell work online and its kinda always a pain if you're not technical. I wonder if a Static site might allow for us to host assets like fonts or illustrations for people to sell. Then we allow them to connect to a payment platform like stripe, in the setting page for the slate.
![image](https://user-images.githubusercontent.com/1757261/93484797-edb68980-f934-11ea-87ac-32e241a2b02a.png)

## Sketchbook view (Basically what Haris mentioned but wanted to document it here)
What if you could open up the app and just start sketching with an iPad and Apple pencil? and just have a public or shared or private notebook?

**Comment by gndclouds** [comment]
## Thinking about how you might choose a view for a slate

I'm sure Haris will have a killer implomentation for something like this but some initial thoughts could be thinking of views through a similar lens to how notion treats them.
![image](https://user-images.githubusercontent.com/1757261/93486029-4d616480-f936-11ea-8732-da28e6b6b5bd.png)


We could have a dropdown on the slate view to toggle views? Since some Slates might benefit from multiple views.

![Group 2](https://user-images.githubusercontent.com/1757261/93486912-4b4bd580-f937-11ea-85be-83e92493b812.png)

And then put details so view sposific settings in the current seetings tab.

![Group 1](https://user-images.githubusercontent.com/1757261/93486943-57d02e00-f937-11ea-8e31-5d8633d0084f.png)

**Comment by jimmylee** [comment]
We agreed to punt this for now but we'll keep it in our peripherals.

**Comment by jimmylee** [comment]
On the back burner.

**Comment by jimmylee** [comment]
After multiplayer
