### ISSUE TITLE
'archive' never finishes; 500 internal server error

### ISSUE THREAD

**Issue by okdistribute** [filecoin-project/slate#287]
I ran into a bug with the published slate application. Upon hitting 'Archive', with 1 PNG file in my public slate, I got a 500 internal server error in the console. Slate UI does not report an error; it simply continues the spinning icon over the 'Make Storage Deal' button.

![Screenshot from 2020-09-15 13-15-21](https://user-images.githubusercontent.com/633012/93260104-c3f33c00-f755-11ea-9ddb-cbd361485751.png)

**Comment by jimmylee** [comment]
Thank you for reporting this @okdistribute 

When this PR lands https://github.com/filecoin-project/slate/pull/239 you will be able to make Filecoin deals against our testnet. More details for that to come soon 👍 

Meanwhile we have added improved error messaging here in a later push that will go out later in the week.

**Comment by jimmylee** [comment]
This is going to be resolved today most likely. But making Filecoin deals may be slow.
