### ISSUE TITLE
Allow download to run in the background + confirmation window for download cancellation

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#288]
# Purpose
I would like to keep the downloading process when I work on something else in Slate. Currently, the download will be automatically canceled when clicking on elsewhere on the screen. 

# Deliverable
- send a confirmation request to the user about before the system cancels the download.
- allow the download to run in the background

**Comment by jimmylee** [comment]
@harisbutt and @martinalong are working on a cool strategy for this.

**Comment by jimmylee** [comment]
@martinalong knocked this out a while ago but we still need an indicator.
