### ISSUE TITLE
Bug: WebApp back button refreshes page.

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#289]
# Purpose

When logged in the app view, the back button within the Slate interface doesn't go back.

![Slate-Back-Bug](https://user-images.githubusercontent.com/1757261/93281137-0b350780-f7fe-11ea-817f-942e5413e6c8.png)

# Deliverable

The <- back icon should take me back to the last page I visited with in the App.

# Dependencies

N/A

**Comment by jimmylee** [comment]
It does for me, is there a specific set of actions you can share to reproduce?

**Comment by jimmylee** [comment]
@gndclouds please check again and provide all of your steps and I will follow you through it all.
