### ISSUE TITLE
Bug: uploading file to other people's slate

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#290]
# Purpose
I tried to test whether or not if I can upload data to other people's slate. And here we go:

<img width="1129" alt="Screen Shot 2020-09-15 at 6 18 44 PM" src="https://user-images.githubusercontent.com/35607644/93281315-b0a99600-f780-11ea-817e-8681649f4f72.png">

It doesn't upload to other people's slate, but the message is confusing.

**Comment by jimmylee** [comment]
Yes we block against that on the server but this would be good to prevent on the client from even getting here.

**Comment by jimmylee** [comment]
Great catch!!

**Comment by jimmylee** [comment]
I'm going to verify.
