### ISSUE TITLE
Bug: File uploads failing as I near the 1gb limit

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#294]
# Purpose

When attempting to upload files near the max storage limit of 1GB my file uploads fail. The odd thing is I still have 20mb left.

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/1757261/93403892-53fec600-f8bb-11ea-8596-82eb2e2cd2c9.png">

# Deliverable

I can upload more files :-) and hit the true size limit.

# Dependencies

N/A

**Comment by jimmylee** [comment]
Working with @andrewxhill on this ✨
