### ISSUE TITLE
Feature: Allow for Slates with the same name

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#295]
# Purpose

Currently, all Slate names need to be unique which limits user agency.

# Deliverable

Allow Slates to appear to have the same name but give them different URLs once the original is claimed. 

For example, if I make `slate.host/gndclouds/books` but `/books` it taken by `slate.host/haris/books` then give me  `slate.host/gndclouds/books-some-string`. (it would be super cool if the URL could auto-complete, so when I enter `gndclouds/books` it know to direct to my books and not `haris/books`)

For reference, I like how are.na implements this a similar feature.
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/1757261/93407290-5e718d80-f8c4-11ea-8db7-d917fa3a5887.png">

# Dependencies

N/A

**Comment by jimmylee** [comment]
@martinalong 

name: "Dogs are fun"
slug/slatename: "dogs-are-fun"

if collision: `dogs-are-fun-${md5}` (5 characters)
if collision again: new md5
