### ISSUE TITLE
Design: Types of Slates look too similar.

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#297]
# Purpose

Yesterday @tarafanlin and I discovered that Slate you can edit and Slates you can view look a little too similar. We should visually communicate when you can edit a slate vs when your viewing a Slate.

gndclouds' Urban Garden
![image](https://user-images.githubusercontent.com/1757261/93488097-90bcd280-f938-11ea-945f-6c2f0bd49fec.png)

Tara's Loom
![image](https://user-images.githubusercontent.com/1757261/93485562-c57b5a80-f935-11ea-840c-56dbf090a3fd.png)

# Deliverable

Clarify the visual styles of personal slates you can edit vs slates you can view.
# Dependencies

N/A

**Comment by jimmylee** [comment]
We talked about this today with @gndclouds and @harisbutt and they are exploring the topic further.

**Comment by jimmylee** [comment]
@harisbutt promised me like Treyway this is going to change really soon.
