### ISSUE TITLE
Bug: Max number of slates has wrong error number

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#298]
# Purpose

Max number of Slates error banner state wrong number.
![image](https://user-images.githubusercontent.com/1757261/93491622-7f75c500-f93c-11ea-8e07-6f5447be71e5.png)

# Deliverable

Error banner should say 50 instead of 20. Better yet don't have a limit 😉

♥️ gndclouds

# Dependencies

N/A

**Comment by martinalong** [comment]
Ok fixed! Change will be pushed when dev -> production
