### ISSUE TITLE
Drag & drop for data upload.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#3]
# Purpose

We want to add drag & drop to the Filecoin Client.

# Deliverable

* Visual UX
* Implementation of drag and drop.

# Dependencies

N/A

**Comment by ziyadbasheer** [comment]
**Drag and Drop design proposal**

- Scale drop-zone
- Animate drop-zone border
- Change drop-zone fill & border color

![drag-and-drop](https://user-images.githubusercontent.com/943672/85542791-b8dab500-b619-11ea-9ad5-8ed1e4109648.gif)

Note: border animation GIF is slow, faster in code: https://codepen.io/ziyadbasheer/pen/GRomzby

**Comment by jimmylee** [comment]
Great idea, thank you !! I think what we'll do is make this popover global so whenever you drag a file over the client you see this interface.

**Comment by ziyadbasheer** [comment]
> Great idea, thank you !! I think what we'll do is make this popover global so whenever you drag a file over the client you see this interface.

In this case I would do away with the change in drop-zone color + scale as my intention was to make the drop-zone clearer in the context of the larger app frame being black/white (grey would indicate activity in the section).

If we are going to overlay it on the window frame let's eliminate scale and color shift, the visual shift to a whole drop-zone by itself is sufficient.
