### ISSUE TITLE
Bug: delete data doesn't always work

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#302]
# Purpose
Deleting data doesn't always remove the data from the interface. 
This error message shows up when I try to delete the "duplicated" **loom_2.jpeg** file for the second time when I thought the first delete attempt didn't work.
<img width="1440" alt="Screen Shot 2020-09-17 at 8 16 44 PM" src="https://user-images.githubusercontent.com/35607644/93556108-bb089300-f92c-11ea-8ccc-d9e4854c44eb.png">

On console log
<img width="1440" alt="Screen Shot 2020-09-17 at 9 31 43 PM" src="https://user-images.githubusercontent.com/35607644/93556282-3e29e900-f92d-11ea-91f0-1a9087c80fa2.png">
<img width="1440" alt="Screen Shot 2020-09-17 at 9 30 49 PM" src="https://user-images.githubusercontent.com/35607644/93556295-44b86080-f92d-11ea-9daa-9d25655f59d9.png">

**Comment by tarafanlin** [comment]
I'm still having this issue @jimmylee

**Comment by jimmylee** [comment]
Are you still having this issue @tarafanlin

**Comment by jimmylee** [comment]
Ongoing problem, I need to update the utility method.
