### ISSUE TITLE
Feature: More detailed storage indicator

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#303]
# Purpose

I see a future in which it's hard to track what is pushing you to your storage limit with in Slate. So we should have a way to see how much a given slate it taking up of your entire storage limit. Currently we display this information this way.

![image](https://user-images.githubusercontent.com/1757261/93548664-4409e380-f99a-11ea-88fb-e56a80df014f.png)

# Deliverable

But maybe we take a note from Apple and have each Slate show in this bar as a reprosentative size?

![image](https://user-images.githubusercontent.com/1757261/93548759-7c112680-f99a-11ea-8b25-06ecac935cf8.png)

# Dependencies

N/A

**Comment by jimmylee** [comment]
@harisbutt has a design for this!

**Comment by jimmylee** [comment]
Get well soon @gndclouds !!
