### ISSUE TITLE
Feature: share slate(s) with invited people

### ISSUE THREAD

**Issue by akuokojnr** [filecoin-project/slate#305]
# Purpose

I think that rather than having only private or public slates, it would be pretty useful to have the ability to invite specific people using their email to view or collaborate on a slate. There are some files you only want to share with a few people and not the whole public.  

# Deliverable

The ability to share slate(s) with people by inviting them to view or collaborate on them.

# Dependencies

N/A

**Comment by jimmylee** [comment]
@harisbutt to explore this, my opportunity to dig into the world of CRDTS
