### ISSUE TITLE
When partial uploads succeed, should just go ahead and add the ones that worked.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#315]
<img width="1470" alt="Screen Shot 2020-09-21 at 11 10 35 PM" src="https://user-images.githubusercontent.com/310223/93848982-ddb5e700-fc5f-11ea-9f1a-bb1edf4a94ea.png">

* Seems like the page freezes.
* On refresh the files weren't added and it doesn't seem the other request was made.

**Comment by martinalong** [comment]
Oh strange. I thought I added handling for that. Do you have a file that consistently fails that I can use to test? That's the main reason I haven't been able to test this case thoroughly
