### ISSUE TITLE
Bug: .epub file zip issue

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#326]
# Purpose

When uploading .epub files some files end in .epub.zip after uploading. This might become an issue once we implement native file previews for .epub documents.

# Deliverable

Ideally, these files would stay .epub to enable future previews.

# Dependencies

N/A

**Comment by jimmylee** [comment]
Making a personal note to ask @gndclouds to provide a epub file that produces this case and then for us to work with Textile to figure out if there is any transformation when retrieving from the gateway to the browser.

**Comment by jimmylee** [comment]
@gndclouds still gonna give me an example file

**Comment by gndclouds** [comment]
The last 7 files I have now tried are not creating the same issue. Will close for now.
