### ISSUE TITLE
Bug: When downloading files from Slate they don't have any extensions.

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#327]
# Purpose

This may cause issues, especially for non-technical users as we scale.

# Deliverable

All downloaded files should have the same extension they were uploaded with.

# Dependencies

N/A

**Comment by jimmylee** [comment]
Will need to test this again.

**Comment by gndclouds** [comment]
Yep! this works! but is really slow, so slow that I thought the download button wasn't working until looking in the console. Perhaps we can use the spinning upload indicator to show the file is being prepared?

![image](https://user-images.githubusercontent.com/1757261/97533874-fef2bb80-19f3-11eb-8264-fea26bdcf849.png)
