### ISSUE TITLE
Help us

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#337]
Here are some things I'd like to see get completed.

## Design System

**New experience pages for Textile/Hub.**
There are experiences pages such as [this one](https://slate.host/_/experiences/make-storage-deal) that need to be updated or deleted. I'd like to have just three experiences today:

+ `<TextileCreateStorageDeal />`
+ `<TextileConfigureSettings />`
+ `<TextileWallet />`
+ `<TextileBucket />`

**Globe improvements**
https://slate.host/_/system/globe

+ Convert those black dots into emoji flags.
+ Add a red number indicator to show peer count.

## Core Product

**Mobile PDFs**
Currently broken.

**Graphs for Analytics** (@jordattebayo)
https://github.com/filecoin-project/slate/issues/164

**Electron**
https://github.com/filecoin-project/slate/issues/129
If you look at this file: https://github.com/filecoin-project/slate/blob/main/pages/_/index.js

+ We can create an electron version with a similar entry point.
+ We're going to build a native application for offline features so we can just focus on a electron version of Slate that does the same thing as https://slate.host

**Epub experience**
https://github.com/filecoin-project/slate/issues/326

**Conversion tools**
https://github.com/filecoin-project/slate/issues/145

**Dropbox desires**
https://www.dropboxforum.com/t5/Dropbox-ideas/idb-p/101002013

+ Worth checking this out to see if there is anything we can do they can't.

**Comment by martinalong** [comment]
We can cross off search debounce now

**Comment by Justin2997** [comment]
I just find this but I was planning to try to add this to Electron as a side project. So if someone want to join me let me know.
