### ISSUE TITLE
CRITICAL: https://slate.host in production (render.com) will not finish uploads past 450mb. Everything is fine local (unless an upload fails and a bucket is bricked)

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#343]
## Updates

* @anurag has proven that the request timeout limit is well over what we need.
* I have updated our express server to have a 15minute timeout limit while we figure out what the problem is.
* I have expanded our memory to 2048mb from the default 512mb.
* Textile has shared their timeout limits.
* **Local**: 1.07 GB file upload works fine locally.
* **Production**: For some reason in production (render.com) 1.07 GB fails after 400mb

## Original Post

I've opened up a conversation with render.com our provider to provide more flexibility around their request timeout, which is probably preventing many users from completing their uploads of larger files.

Since we store nothing locally on render.com, I'm just hoping to have an extended request timeout so our watermarked NodeStream (3mb) can be passed through to Textile's servers.

### API Endpoint File:
https://github.com/filecoin-project/slate/blob/main/pages/api/data/%5Bupload%5D.js#L27

* very simple API request, just form/multipart
* saves the success reference URL (from Textile) to our postgres DB to be picked up by another request later on.

### Upload Source Code:
https://github.com/filecoin-project/slate/blob/main/node_common/upload.js

* we just work with streams, no local files get kept on render.com servers.

This has to happen on render.com because the `form/multipart` request that hits their servers first.

I've spoken to @anurag and let them know we have some flexibility on time, and just grateful for the support and quick response. ❤️ 

Sorry about the thrash earlier @andrewxhill @carsonfarmer, I should have checked this earlier.

**Comment by anurag** [comment]
@jimmylee can you share the timeouts on Textile's servers?

**Comment by sanderpick** [comment]
Hey @anurag, Textile guy here... the only WebSocket timeouts that come to mind are from the Nginx Ingress Controller:

```
proxy_connect_timeout     60s;
proxy_send_timeout          3600s;
proxy_read_timeout           3600s;
```
See [this reference](nginx.org/en/docs/http/ngx_http_proxy_module.html) for explanations on those. tl;dr, those timeouts only apply to the initial connection and successive reads/writes, not the whole request. There's no upper limit on how long a total request can take.

**Comment by jimmylee** [comment]
Will resolve: https://github.com/filecoin-project/slate/issues/294

**Comment by anurag** [comment]
From what we can tell so far, Slate's Express server seems to be ending the connection in 60 seconds. Could this be a Node/Express level timeout?

**Comment by jimmylee** [comment]
Will revise this ASAP, sorry thats embarrassing on my part :(

**Comment by jimmylee** [comment]
<img width="1910" alt="Screen Shot 2020-10-03 at 8 53 54 PM" src="https://user-images.githubusercontent.com/310223/95006565-dd501100-05ba-11eb-9306-998256abe575.png">

<img width="2051" alt="Screen Shot 2020-10-03 at 8 55 43 PM" src="https://user-images.githubusercontent.com/310223/95006568-e214c500-05ba-11eb-8eca-f693c6bb1de6.png">

**Comment by jimmylee** [comment]
With the adjusted timeout I'm able to get 2.09 GB of lego images up, will now deploy this to production for your testing. Please make a new account.

**Comment by jimmylee** [comment]
## In production

* Seems to timeout for requests that take a little longer
* Going through https://slate.host, so the request is processed through https://slate.host and then to Textile.
* Uses the code paths we have discussed before, but now with an **8 minute timeout**.

<img width="1749" alt="Screen Shot 2020-10-03 at 9 16 56 PM" src="https://user-images.githubusercontent.com/310223/95006870-d545a080-05bd-11eb-94f2-cdc3dba70ebc.png">

## Local development

* Same code as production
* Goes through localhost, and then straight to Textile
* I am able to finish the full upload of 2GB

<img width="1748" alt="Screen Shot 2020-10-03 at 9 11 58 PM" src="https://user-images.githubusercontent.com/310223/95006884-032ae500-05be-11eb-81eb-da739919c2f4.png">

What I could do @anurag is give you our env development env variables so you can run it locally, I'm pretty sure you will be able to finish the transfer.

**Comment by jimmylee** [comment]
We're finding that 4GB files won't work, we are making sure to test something smaller to account for the `.textileseed` and maybe some nuance.

**Comment by anurag** [comment]
I was able to create a simple Python server that waits a specified amount of time before returning. Using this, I was able to run a request that took 300 seconds to complete on Render; indicating the issue might not be on Render's end and could have something to do with the configuration for Slate and/or Textile in production mode when not running on localhost.

```
❯ time curl -vvv https://flask-slow.onrender.com/slow/300/
*   Trying 34.83.64.96:443...
* TCP_NODELAY set
* Connected to flask-slow.onrender.com (34.83.64.96) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=flask-slow.onrender.com
*  start date: Oct  4 22:38:29 2020 GMT
*  expire date: Jan  2 22:38:29 2021 GMT
*  subjectAltName: host "flask-slow.onrender.com" matched cert's "flask-slow.onrender.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55ac843c5db0)
> GET /slow/300/ HTTP/2
> Host: flask-slow.onrender.com
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!


< HTTP/2 200
< content-type: text/html; charset=utf-8
< date: Mon, 05 Oct 2020 00:33:06 GMT
< server: gunicorn/20.0.4
< content-length: 2
<
* Connection #0 to host flask-slow.onrender.com left intact
OK

curl -vvv https://flask-slow.onrender.com/slow/300/  0.03s user 0.02s system 0% cpu 5:00.24 total
``

**Comment by jimmylee** [comment]
In this commit I've gone and set all the timeouts using known methods for express servers.

https://github.com/filecoin-project/slate/commit/2d96a34007a293375b3fcbbbc82236bad880192c

configured my own servers timeouts to `15 minutes`

```
  server.keepAliveTimeout = 15 * 60 * 1000;
  server.headersTimeout = 450 * 1000;	  server.headersTimeout = 16 * 60 * 1000;
```

and 

```
  const listenServer = server.listen(Environment.PORT, async (e) => {
    if (e) throw e;	    if (e) throw e;

    console.log(`[ slate ] client: http://localhost:${Environment.PORT}`);	    console.log(`[ slate ] client: http://localhost:${Environment.PORT}`);
  });	  });

  listenServer.setTimeout(15 * 60 * 1000);
```

and

```
  server.all("/api/:a/:b", async (r, s) => handler(r, s, r.url));	    r.setTimeout(15 * 60 * 1000, function() {
      console.log("REQUEST TIMED OUT");
    });

    s.setTimeout(15 * 60 * 1000, function() {
      console.log("RESPONSE TIMED OUT");
      s.send(408);
    });

    return handler(r, s, r.url);
  });
  server.all("/api/:a/:b", async (r, s, next) => {
    r.setTimeout(15 * 60 * 1000, function() {
      console.log("REQUEST TIMED OUT");
    });

    s.setTimeout(15 * 60 * 1000, function() {
      console.log("RESPONSE TIMED OUT");
      s.send(408);
    });

    return handler(r, s, r.url);
  });
``` 

I'm now going to try to deploy ourselves to another provider and see if the bug exists

**Comment by jimmylee** [comment]
I can also verify that my node server on `https://filecoin.onrender.com` has a 15 minute timeout for `GET` requests

```
RIVERLANDS:slate riverlands$ curl -vvv https://filecoin.onrender.com/please-dont-use-timeout
*   Trying 34.83.64.96...
* TCP_NODELAY set
* Connected to filecoin.onrender.com (34.83.64.96) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=filecoin.onrender.com
*  start date: Aug 29 15:35:59 2020 GMT
*  expire date: Nov 27 15:35:59 2020 GMT
*  subjectAltName: host "filecoin.onrender.com" matched cert's "filecoin.onrender.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb60c80f600)
> GET /please-dont-use-timeout HTTP/2
> Host: filecoin.onrender.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
```

Where the endpoint it is hitting is:

```
  server.get("/please-dont-use-timeout", async (r, s) => {
    console.log("[ forbidden ] someone is using your testing timeout");

    await sleep(15 * 60 * 1000);

    return s
      .status(200)
      .send({ decorator: "15_MINUTE_TEST", data: { success: true } });
  });
```

**Comment by jimmylee** [comment]
### Small Update

So I put together an S3 implementation on its own server: https://github.com/jimmylee/next-s3 just so I could compare the experience between Textile and S3.

I thought this would be very revealing, but I actually can't get any uploads beyond 500mb to finish locally (800mb doesn't work, fail silently at 700mb).

With Textile at least I'm still able to get a 2GB file uploaded locally.

Very curious whats going on... with Amazon S3 I get a silent failure and `net::ERR_CONNECTION_RESET` and no throw server-side, I've tried a number of configurations but just haven't had any luck.

**Comment by jimmylee** [comment]
Closing this issue in favor of https://github.com/filecoin-project/slate/issues/366 because I think I am getting closer to the root cause.
