### ISSUE TITLE
back button not working for the tab

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#348]
# Purpose
back button doesn't work when I click between my slates and following
<img width="1112" alt="Screen Shot 2020-10-01 at 7 11 50 PM" src="https://user-images.githubusercontent.com/35607644/94881308-f7062280-0419-11eb-9097-602b7504f100.png">

**Comment by jimmylee** [comment]
Lets wait for the dust to settle on design changes before we tackle this one.

**Comment by jimmylee** [comment]
Still waiting for the dust to settle.
