### ISSUE TITLE
feature: parallel document

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#369]
# Purpose
Exploring how we can use a parallel structure for indexing file annotations, documents in a slate, or multiple connected slates.

# Moodboard
http://lines.thecafesociety.org/lines/my-library/#790
![](https://user-images.githubusercontent.com/35607644/95685787-e179c100-0bae-11eb-9852-cc8b37a74ecf.png)

http://www.makecommoningwork.fed.wiki/view/federated-wiki/view/commons/view/commoning/view/dimensions-of-commoning
![](https://user-images.githubusercontent.com/35607644/95685826-33bae200-0baf-11eb-98d2-9264afda439d.png)

https://slate.host/tara/slate/cid:bafybeih6cde7ovxso5uuuv4joq7diwyrwp45dcrxnphheh3fuk6sxwte7y
![](https://user-images.githubusercontent.com/35607644/95685908-a2983b00-0baf-11eb-8c43-0690cae3bc13.png)

**Comment by jimmylee** [comment]
I'm a huge fan of these explorations and references. Thank you @tarafanlin !

**Comment by gndclouds** [comment]
Should check out the Andy Matuschak's [Evergreen notes](https://notes.andymatuschak.org/z4SDCZQeRo4xFEQ8H4qrSqd68ucpgE6LU155C?stackedNotes=z6bci25mVUBNFdVWSrQNKr6u7AZ1jFzfTVbMF)
<img width="1366" alt="Screen Shot 2020-10-24 at 7 29 59 AM" src="https://user-images.githubusercontent.com/1757261/97061839-e7b66700-15ca-11eb-91a0-7e0d093ac12f.png">
