### ISSUE TITLE
Feature: add og-image links so when links to slates are shared they look awesome

### ISSUE THREAD

**Issue by jesseclay** [filecoin-project/slate#370]
# Purpose
Slate is awesome, but when I go to share a particular slate or image from slate on Twitter, Slack, etc.. I'm met with a sad placeholder image:

![image](https://user-images.githubusercontent.com/1719763/95805525-3ad71280-0ccb-11eb-8265-882f0715b16c.png)

# Deliverable
For every page on slate we should link, in [og: head tags](https://ogp.me/) to some sort of image asset that represents the slate or individual image being shared. This will make shares on social media even more engaging and drive more users to slate.

Can link to different sizes and formats, so I defer to the team on how best to showcase any particular slate or image with these assets. Basically most anything is better than nothing! :)

# Dependencies

N/A

**Comment by martinalong** [comment]
hey @jesseclay ! Funny you mention this, we're actually working on this right now. It should go out soon along with our revamped layout editor and slate editing page. 

The situation with twitter/slack preview images is that if they're over a certain size, they aren't shown. Which seems to be what's happening here. After the update, users will have the option to choose which image is the preview image and we'll save a version of it that's under the size limit for previews.

**Comment by jesseclay** [comment]
Of course you're already on it. Slate team rocks!!

**Comment by jimmylee** [comment]
@martinalong knocked this one out! It looks awesome

![Uploading Screen Shot 2020-10-23 at 4.08.23 PM.png…]()
