### ISSUE TITLE
Database cleanup

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#377]
# Purpose

Database formatting inconsistencies have grown over time. We've been putting stop gaps on the front end to transform these data types into the ones we want, it but it would be better to just restructure things.

# Deliverable

- Slate files:
   - Add **cid** and **size** (keep url there in case we want other types of urls in the future)
   - Find all the places with https://undefined and remove the undefined
- Data files:
   - Remove **icon**
   - Replace ipfs with cid

**Comment by jimmylee** [comment]
I owe Martina two queries

**Comment by jimmylee** [comment]
This is probably done we can re open if it needs to be reopened.
