### ISSUE TITLE
Simplify Miner Selection

### ISSUE THREAD

**Issue by ihlec** [filecoin-project/slate#382]
# Purpose
Simplify selecting miners for storage deals.

It is cumbersome to copy miner ids from the Miner-view.

# Deliverable
Create a list where miner ids can be selected from.
The list exists already in the Miner-view, but needs to be present in the Storage-Deal-view (e.g. as a dialog with checkboxes).

**Comment by jimmylee** [comment]
I love this idea, thank you @ihlec!

**Comment by jimmylee** [comment]
Please use https://file.app to find your miner for now.
