### ISSUE TITLE
Global toasts & progress state

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#4]
# Purpose

* Users need to see global toasts with english that explains whats happen.
* More progress bars for work that is being done.

# Deliverable

* Visual UX
* Implementation

# Dependencies

N/A

**Comment by ziyadbasheer** [comment]
Can we get an example of what we expect these toasts to look like? Full-width at the top of the app window frame?

What type(s) of progress bars for which functions are we looking at?

**Comment by jimmylee** [comment]
@ziyadbasheer I can probably include some explorations or do a quick and dirty implementation we can built upon later. Thanks for bringing this up.

Progress bars:
+ Data transfer between peers and miners
+ Infinite for tasks that don't have a stop time
+ Things to look at when we're configuring the application behind the scenes.

Toasts
+ Whatever makes sense, I'm excited to get some design help here. We can make this element really fun :)
