### ISSUE TITLE
Configure Slate to build on Windows 10

### ISSUE THREAD

**Issue by uonai** [filecoin-project/slate#40]
# Purpose

Slate application currently fails to build on Windows 10. There are conflicts in the _textile_ and _improbable-eng_ packages. Lotus DevNet and Powergate appear to be work as expected.

# Deliverable

Resolving this issue will ensure that users can build Slate on Windows 10.

# Dependencies

N/A

**Comment by jimmylee** [comment]
Replacement issue: https://github.com/filecoin-project/slate/issues/129
