### ISSUE TITLE
Implement shift + click

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#400]
# Purpose

<img width="1184" alt="Screen Shot 2020-10-31 at 3 15 53 PM" src="https://user-images.githubusercontent.com/310223/97791104-00ef8280-1b8c-11eb-95fb-2478af8d825e.png">

I should be able to shift + click and select many items at once to make it easier to manage my library.

# Deliverable

* Implement shift + click without causing any regressions.

**Comment by akuokojnr** [comment]
@jimmylee we can close this issue now since it has been fixed with PR #456
