### ISSUE TITLE
Textile & Filecoin integration tasks

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#410]
## Textile & Filecoin

These are important tasks to help us get through

* November 2020 to July 2021 tasks: https://github.com/filecoin-project/slate/issues/411
* Where Slate:WWW Failed: https://github.com/filecoin-project/slate/issues/409

I had originally posted the list in our shared-textile Slack channel but I think it is more appropriate to keep a check list of the issues here.

#### grantFIL
- [ ] **this task is complete**.
* using `dropFil`, we can control when a Textile Hub user gets Filecoin.
* @asutula claims the name has been contested, but I haven't received any updates here.
* once `dropFil` is enabled I can pre-generate thousands of libp2p tokens for the Coinbase Earn campaign targeted towards December (if they still want to work with us).
* name change to grantFIL.
* still in design phase.

#### Retrieval buckets
- [ ] **this task is complete**.
* A retrieval bucket is a bucket that is created on the Slate:WWW user's behalf when they make a retrieval deal.
* Because we are retrieving a bucket, we can load all of the data directly into a Slate:WWW user's account. This creates an awesome user experience.
* I'd like to explore the economics around this, so the sooner this lands the better.
* I'm assuming @carsonfarmer is the owner of this task.

#### Customize default storage configuration settings for Hub
- [x] **this task is complete**.
* I just need @asutula to remind me if there is a way to do this so I can restore a settings page on Slate.

<img width="1412" alt="Screen Shot 2020-11-08 at 8 31 09 PM" src="https://user-images.githubusercontent.com/310223/98500445-5d444900-2201-11eb-8e6b-c544e4a1d37f.png">

#### Miner Index
- [ ] **this task is complete**.
* I would love an API call I can make, or a method I can call thats part of Textile's Hub that provides a list of the current miner reputations.

#### Parallel Uploads
- [ ] **this task is complete**.
* Since uploads take a long time from USWest to USEast, parallel uploads would help performance.
* I know @carsonfarmer would like this too, but there is no timeline on when it is possible.

#### Fixing a hack with importing @improbable-eng/grpc-web
- [x] **this task is complete**.
* I still need to check if: https://github.com/slate-engineering/shovel/blob/main/package.json#L21 is necessary.

#### Archive Receipts
- [x] **this task is complete**.
* https://github.com/textileio/textile/issues/385
* I need a response that happens immediately on `bucket.archive` that returns a response with something to track the job with.
* Ideally it returns the `jobId`
* Critical for the Coinbae Earn campaign.

#### Get all jobIds for a LibP2P token.
- [x] **this task is complete**.
* I just want to get all the running jobIds for any given user.

We already use 

```
    const result = await power.listStorageDealRecords({
      ascending: false,
      includePending: true,
      includeFinal: true,
    });
```

But this doesn't work for deals that aren't getting accepted. So we still need the `jobId`.

#### What is the endpoint to get jobId logs?
- [ ] **this task is complete**.
* Is there an endpoint?
* What is the Textile Hub method for this?
* I don't need them to be live, refreshing is fine.

#### How do repair deals?
- [ ] **this task is complete**.
* https://github.com/textileio/textile/issues/389
* Very useful to have a method for deal repair since miners can go down
* power.listStorageDealRecords still lists those deals as successful.

**Comment by asutula** [comment]
Great summary @jimmylee. 

Setting the default archive storage config is [already supported in `js-hub` client](https://github.com/textileio/js-textile/blob/master/packages/buckets/src/buckets.ts#L731)

For the remaining issues related to Powergate/Filecoin storage via Bucket archiving, here are the relevant issues on the Textile side:

https://github.com/textileio/textile/issues/395
https://github.com/textileio/textile/issues/396
https://github.com/textileio/textile/issues/397
https://github.com/textileio/textile/issues/385
https://github.com/textileio/textile/issues/398
https://github.com/textileio/textile/issues/399
https://github.com/textileio/textile/issues/389

**Comment by jimmylee** [comment]
https://github.com/textileio/textile/issues/400 - Some confusion I'm having over the Pow module in hub.

**Comment by asutula** [comment]
You can check "Archive Receipts" as complete (https://github.com/textileio/textile/pull/412).

**Comment by asutula** [comment]
"Fixing a hack with importing @improbable-eng/grpc-web" is also complete
