### ISSUE TITLE
layering order (z-index) for grid layout

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#417]
wish there is a way to do send objects to back/front in the grid layout.

**Comment by martinalong** [comment]
Would you say that the z-indexing system we have right now isn't enough? Like where the last thing you clicked on gets sent to the front automatically?

**Comment by tarafanlin** [comment]
> Would you say that the z-indexing system we have right now isn't enough? Like where the last thing you clicked on gets sent to the front automatically?

I'm not sure if there are enough cases. 
But this morning when I put together this slate: https://slate.host/tara/memory-palace. 
Trying to layer small files objects on top of the bigger one can be difficult. 
The big file will cover the smaller on, making them inaccessible. 
I had to move it away and rearrange.

**Comment by jimmylee** [comment]
I think a way to configure by integer would be nice.

**Comment by tarafanlin** [comment]
closing this for now because we might solve the problem altogether with slate canvas
