### ISSUE TITLE
Test reading PDFs on mobile.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#419]

**Comment by autonome** [comment]
Ditto on desktop. I get download prompt instead of the browser rendering, so maybe needs headers fixed.

**Comment by jimmylee** [comment]
<img width="1465" alt="Screen Shot 2020-11-23 at 4 42 11 PM" src="https://user-images.githubusercontent.com/310223/100031590-dd92ae80-2daa-11eb-9739-13c2a2851b51.png">

Will need to know what browser you're testing with :) I think we can use @akuokojnr full screen strategy for unity games for pdfs too. we'll see.

**Comment by autonome** [comment]
Firefox Nightly

**Comment by autonome** [comment]
Hm, maybe an extension... cannot repro on Firefox regularé.
