### ISSUE TITLE
Profile: Intermittent 500 when updating avatar

### ISSUE THREAD

**Issue by cwaring** [filecoin-project/slate#422]
## Issue
Error 500 received when updated user profile avatar.

## Recreate
+ navigate to: https://slate.host/_?scene=V1_NAVIGATION_PROFILE_EDIT
+ select new jpeg avatar
+ 500 error upon save

I don't have an error log as I'm unable to recreate this again now, opening to capture additional details if it happens again.

**Comment by jimmylee** [comment]
This is a fascinating one! Thank you for catching it, I see it too.

**Comment by jimmylee** [comment]
Patched! Thank you @cwaring 

<img width="1515" alt="Screen Shot 2020-11-17 at 10 21 44 AM" src="https://user-images.githubusercontent.com/310223/99430928-d22d1800-28be-11eb-8e86-822932027b3b.png">
