### ISSUE TITLE
Profile: avatar does not allow PNG upload

### ISSUE THREAD

**Issue by cwaring** [filecoin-project/slate#423]
## Issue
When adding a PNG image for your profile image .

## Recreate
+ navigate to: https://slate.host/_?scene=V1_NAVIGATION_PROFILE_EDIT
+ select new PNG avatar
+ error "some of your file cannot be uploaded"

![2020-11-17 at 15 20 30](https://user-images.githubusercontent.com/106938/99408872-a32b9c00-28e8-11eb-8a7b-5ae76f17c21a.png)

## Resolution
+ Restrict the avatar upload to supported filetypes (assuming that PNG isn't supported)

**Comment by jimmylee** [comment]
PNG is supported, this is a strange bug.

**Comment by jimmylee** [comment]
<img width="1515" alt="Screen Shot 2020-11-17 at 10 21 44 AM" src="https://user-images.githubusercontent.com/310223/99430861-be81b180-28be-11eb-8925-918d5c1e2062.png">

* Patched, we had a few regressions here from a layout rework.
