### ISSUE TITLE
When Slate is idle too long, reconnect Slate's websocket client to the Fiji websocket server

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#437]
When you

* Put your computer to sleep
* Have an idle browser tab

You may lose your web socket connection, in this case we need to

* Reconnect to FIJI to receive updates

**Comment by martinalong** [comment]
Ok I'm thinking this will be something that: when you do an action, it checks if you are connected to the websocket. And if not, reconnects you. Just still figuring out where's the best place to do this check

**Comment by martinalong** [comment]
This should be fixed now. I tested it by putting my computer to sleep then using slate, and it reconnected automatically
