### ISSUE TITLE
Redesign: I don't like how the CTA to do anything is below the fold after a user creates an account.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#440]
<img width="1477" alt="Screen Shot 2020-11-21 at 1 03 45 PM" src="https://user-images.githubusercontent.com/310223/99887542-12133880-2bfa-11eb-8e44-fbf9913a2455.png">

* When a new user creates an account, there is no CTA on the screen in most cases
* It seems like a user will have to scroll to the bottom to create an account

Suggestions

* Add a CTA above the fold.

**Comment by martinalong** [comment]
What do you mean by this? A bit confused

**Comment by jimmylee** [comment]
<img width="1524" alt="Screen Shot 2020-11-27 at 6 04 20 PM" src="https://user-images.githubusercontent.com/310223/100491749-07194600-30db-11eb-8676-ef3420db30ff.png">

<img width="1524" alt="Screen Shot 2020-11-27 at 6 04 23 PM" src="https://user-images.githubusercontent.com/310223/100491753-0c769080-30db-11eb-94fb-640db73d1363.png">

* You have to scroll down to click this button, it should be somewhere above the fold and you shouldn't have to scroll down to see it.

**Comment by martinalong** [comment]
We're going to use the onboarding modals tara is creating for the first touch experience instead of this gif (especially since it's pretty outdated), so closing this for now.
