### ISSUE TITLE
When a user deletes a Slate, they should be prompted with a confirm.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#441]
* We should confirm with the user if they are sure. And warn them of the consequences, you can use `window.confirm` for this.

**Comment by martinalong** [comment]
![image](https://user-images.githubusercontent.com/33686587/100487955-235bb980-30c0-11eb-94bf-0e4dd647758e.png)
I think there already is a warning. Unless you want to change the wording?

**Comment by jimmylee** [comment]
This is good enough! Thanks, it might have been from another path that did not have a `window.confirm`
