### ISSUE TITLE
Hitbox for Navigation is too small, Please add an 8px buffer around it.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#449]
<img width="1375" alt="Screen Shot 2020-11-24 at 4 22 37 PM" src="https://user-images.githubusercontent.com/310223/100166318-4a707c00-2e71-11eb-9b74-d5d5c0a4c129.png">

* The hitbox for the navigation is too small and sometimes results in a click miss.

**Comment by martinalong** [comment]
fixed
