### ISSUE TITLE
Directory should show indicators for when you have new requests.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#450]
<img width="760" alt="Screen Shot 2020-11-24 at 4 26 32 PM" src="https://user-images.githubusercontent.com/310223/100166552-d84c6700-2e71-11eb-878e-05c375c89bb8.png">

* Directory should show indicators for new requests.
* Directory requests should also update in real time when a user makes them.

**Comment by martinalong** [comment]
Closing since we no longer have friend requests anymore. We will have an indicator on the notifications icon if there are new people who follow you though
