### ISSUE TITLE
Add the correct query parameters when looking at Slate pages when logged in.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#473]
<img width="1510" alt="Screen Shot 2020-12-10 at 9 37 15 AM" src="https://user-images.githubusercontent.com/310223/101808574-5b54fa80-3acb-11eb-8763-255997435868.png">

* This case isn't captured, when viewing a Slate for a logged in user, should be trivial just to add the query strings using a library like `qs`

**Comment by jimmylee** [comment]
I know its annoying that we don't have real web routes for signed in pages. Just in case you are all chatting about this privately.

**Comment by martinalong** [comment]
Closing this since no longer relevant. Converted to the external style slate.host/user/slatename
