### ISSUE TITLE
Surface error message from server

### ISSUE THREAD

**Issue by listenaddress** [filecoin-project/slate#481]
# Purpose

Wasn't sure why my storage deal wasn't working.

# Deliverable

Correct error message should be shown. 

When I try to make a storage deal on `https://slate.host/_?scene=V1_NAVIGATION_ARCHIVE`, I get a "Whoops something went wrong! Please try again.". As a user, it's not clear why this is happening. I see the server is returning a message that says "Your deal size of 1.33 MB is too small. You must provide at least 100MB.", so we prob just need to surface that to the UI. 

Thanks for your awesome work y'all! 

# Dependencies

N/A

**Comment by jimmylee** [comment]
Thanks for sharing this, we'll take a look soon :)

**Comment by martinalong** [comment]
Added custom messages for each of the error types! Change will be pushed to production soon
