### ISSUE TITLE
Can't download the original game zip

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#484]
<img width="1858" alt="Screen Shot 2020-12-23 at 10 39 51 AM" src="https://user-images.githubusercontent.com/310223/103027726-433d9c00-450b-11eb-81bd-4b179344d45b.png">

* When I click on this link all I get is the index.html file, that probably means we need to make a special case here for downloading the unity game archive that was uploaded before.
* If this isn't possible, then we'll need to think of a better solution here.

**Comment by jimmylee** [comment]
@akuokojnr is this working for you in production? just want to verify.

**Comment by akuokojnr** [comment]
@jimmylee It works great for me. I've tested it several times.
