### ISSUE TITLE
Sign up page improvements

### ISSUE THREAD

**Issue by darzyx** [filecoin-project/slate#486]
# Purpose

On the initial signup page I see two UX issues:
* A user might accidentally enter the wrong password on the first try, and they have no way of knowing if they did until they try to sign in again.
* Clicking on the terms of service navigates you away from the signup page, so you have to look for a way to get back there again.

# Deliverable

* Add functionality to toggle password visibility. This lets users verify they typed in the correct password without lowering the conversion rate as an added password confirmation field would.
* Open the terms of service page in a new tab instead of in the same tab. This keeps the user on the signup page if they simply close the tab for the terms of service.

# Dependencies

None.

**Comment by jimmylee** [comment]
Thank you for this!!

**Comment by martinalong** [comment]
Added! Will be pushed to production soon. Thanks!
