### ISSUE TITLE
back and forth buttons not updating the media content in carousel view

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#489]
# Purpose

*back and forth buttons are not updating media content in carousel*

https://user-images.githubusercontent.com/35607644/103790125-a6442e00-4ff5-11eb-8168-146551562797.mov

# Deliverable

*I would expect the media content to be updated when I click on the back and forth buttons. That's how it works for other file types. Is there a reason why we don't do it? or is it just a bug?*

# Dependencies

N/A

**Comment by martinalong** [comment]
I thought about it while implementing this and I think it would be more annoying than useful for it to include carousel pages bc then if you nagivated to a slate, looked through a few carousel elements, then wanted to go back, you'd have to click back a bunch of times before you could get back to the previous page.

The way we have it now, if you really wanted to go back to the previous carousel pages, you could just click the left / right buttons and easily get to them.

**Comment by tarafanlin** [comment]
oh I meant left/right when I say back/forth buttons.
so currently, the left/right buttons won't let you navigate through carousel content (not the sidebar) for media files.
try play a song here and use the left/right button, it doesn't change the content: https://slate.host/blue2fly/music

Is this by design? but it's not consistent with the interactions for other file types.

**Comment by martinalong** [comment]
Ok fixed now! Was just a matter of adding a key to the video and audio tags so that react could identify them as different when the URL changed (see [here](https://stackoverflow.com/questions/41303012/updating-source-url-on-html5-video-with-react) for explanation)
