### ISSUE TITLE
We ran into an issue while creating that storage deal

### ISSUE THREAD

**Issue by garysdevil** [filecoin-project/slate#493]
![image](https://user-images.githubusercontent.com/41293784/105357404-c13ab300-5c2f-11eb-9b5f-1295cb8307d8.png)

**Comment by jimmylee** [comment]
We need better error reporting here for sure. Thanks for reporting this!

**Comment by garysdevil** [comment]
> We need better error reporting here for sure. Thanks for reporting this!

And how to delete all file listed, I need to delete them one by one, I am crazy now

**Comment by jimmylee** [comment]
We're going to revisit that once we add back parallel uploads. Sorry about that, we had to make adjustments to the user experience that we never revisited, we'll add back batch deletions.

**Comment by jimmylee** [comment]
We'll be going in a new direction in a couple of weeks. Sorry about this.
