### ISSUE TITLE
Video not show

### ISSUE THREAD

**Issue by alanshaw** [filecoin-project/slate#527]
# Purpose

Want to see video.

# Deliverable

Visible video.

I wanted to see if I could use slate to store demo videos but it not show.

<img width="1440" alt="Screenshot 2021-02-12 at 16 26 32" src="https://user-images.githubusercontent.com/152863/107794366-4147ca80-6d4f-11eb-82c7-78b448b1d49e.png">

**Comment by cwaring** [comment]
Mind dropping the file link / cid here? I'll dig into this one

**Comment by jimmylee** [comment]
Thanks @alanshaw for reporting!

**Comment by cwaring** [comment]
Looks like the current video player has issues with `.mov` files. Will investigate alternatives soon
