### ISSUE TITLE
When clicking Play on Unity, the carousel closes

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#533]
Steps to reproduce:

Visit: https://slate.host/jim/unity-games
Open game: 

<img width="1662" alt="Screen Shot 2021-02-15 at 5 30 54 PM" src="https://user-images.githubusercontent.com/310223/108007794-a996e600-6fb3-11eb-8c85-14e6dfc5f3c9.png">

Click "Play"

**Expected**: I can play the game
**What actually happens**: the game closes.

**Comment by martinalong** [comment]
I suspect the reason for this might be that feature we added where clicking on the translucent background behind the carousel closes the carousel. Maybe we can disable this for unity games since the behavior seems to be unpredictable with those
