### ISSUE TITLE
Research: Ask other products to switch over to our content addressed bucket storage.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#55]
# Purpose

Slate will support [Textile buckets](https://blog.textile.io/first-look-at-textile-buckets-dynamic-ipfs-folders/), that will open doors for products to switch from services like `google-buckets`, `amazon-s3`.

Let's make a list of product/companies that can switch over when we have a reliable service!

## Deliverable

+ Web service has to be completed (user accounts, etc).
+ API Keys need to be completed (key management, etc).
+ Examples of how to upload images through our libraries to Slate using the API key.

## Notes

+ https://github.com/googleapis/nodejs-storage

**Comment by gndclouds** [comment]
Wanted to take a pass at an initial list of some possible companies. 

- [Ello](https://ello.co/) 
- [MakeSpace](https://makespace.fun) 
- [Are.na](https://www.are.na)
- [Futureland](https://futureland.tv/)
- [Kinopio](https://kinopio.club) 
- [Dev.to](https://dev.to)
- [Mastodon](https://mastodon.social/about) 
- [Glitch](https://glitch.com)
- [Special Fish](https://special.fish)
- [Reduct](https://reduct.video) 
- [Itch](https://itch.io)

**Comment by gndclouds** [comment]
I wanted to list a few more examples of markets we could also look into, who likely could benefit from Slates Textile Buckets.

- Real Estate Companies for example [Zillow](https://zillow.com)
- Location-based discovery services like [Yelp](https://yelp.com) or [Foursquare](https://yelp.com) (Anyone know of an open-source competitor to these?)
- Asset Marketplaces like [Unity Asset Store](https://assetstore.unity.com), [Game maker](https://gameassetsmarketplace.com/3d-assets) and [Sketch Fab](https://sketchfab.com/tags/marketplace)
- Podcast sites
- CMS integration thinking of [ghost](https://ghost.org)

**Comment by jimmylee** [comment]
Great idea! This is super helpful. I can't wait to show some code examples of how we can make it easier for them to change in the short term.
