### ISSUE TITLE
Design: We need to work on our Typography guidelines!

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#56]
# Purpose

We only needed `H1`, `H2`, and `P`, and that was good enough for now. Lets add some more, and also explore language features with [Inter](https://rsms.me/inter/) and [Fira](https://github.com/tonsky/FiraCode).

# Deliverable

* New options, `OL`, `UL`, `H3`, `H4`, etc
* More case examples of using the typography.
* Any fun enhancements you can think of.
* Parity with something like [Tachyons](https://tachyons.io/#style)

**Comment by gndclouds** [comment]
@tarafanlin 
- [ ] Stying new text element (`OL`, `UL`, `H3`, `H4`)
- [ ] Creating bundles of text element tags and displaying CSS value.

@gndclouds 
- [ ] Creating example of the text element in different series like `:hover` and `:visited`
- [ ] Show all font in abc / 123 with ligature option.

> Any fun enhancements you can think of.

- Link hover states
- Add non-latin text support
