### ISSUE TITLE
Make nifty shortcuts obvious (available) to users 

### ISSUE THREAD

**Issue by akuokojnr** [filecoin-project/slate#560]
# Purpose

Currently, Slate has the following shortcuts which make data management Slate very easy:
- Drag to select items
- Press shift + click to select a range of items
- Press Ctrl + F to open Lens

Except for the key binding to open Lens, the rest are unknown to the user and cannot be easily found. Can we find a way to group these and make them obvious to the user?

# Deliverable

Make nifty shortcuts obvious or available to users.

# Dependencies

N/A

**Comment by martinalong** [comment]
Yeah! You can take a look at what we did for the individual slate pages. If you click edit then hover over the command symbol, a tooltip appears with the keyboard shortcuts. You could take the same component and use it for the data page if you want

**Comment by akuokojnr** [comment]
Alright. I am going to work on that.
