### ISSUE TITLE
Navigation design

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#611]
## Purpose
Navigation design 2.0 to accommodate the new product architecture

## Specs
- mobile & web
- logo
- logged out view

## Design
https://www.figma.com/file/qFvdEZIkSDz0ZV26vnfkNm/?node-id=592%3A636

**Comment by HardHead995** [comment]
Awesome

**Comment by HardHead995** [comment]
5ndndje

**Comment by martinalong** [comment]
So the only real hold up on this is just design. If you have a design in mind @tarafanlin we can actually put it into effect right away. But yeah this is something that has been annoying me as well and is on the upcoming to-do's

**Comment by HardHead995** [comment]
Yo @tarafanlin
