### ISSUE TITLE
When a new user creates a "Private Slate", the redirection is broken.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#621]
When a new user, or existing user creates a Slate using the GUI shown below, after they are finished they are redirected to the "No access page" page.

After they are redirected to a blank page and perform a hard refresh (MacOS Chrome: CMD+SHIFT+R) they are still redirected to "We were unable to locate that slate" and they have to close their whole session to get to their Slate.

### Reproduction
User starts by creating a private Slate.

<img width="1480" alt="Screen Shot 2021-03-09 at 3 26 33 PM" src="https://user-images.githubusercontent.com/310223/110552589-7d6f1080-80ec-11eb-8d68-a7c5db4c4037.png">

<img width="1480" alt="Screen Shot 2021-03-09 at 3 31 37 PM" src="https://user-images.githubusercontent.com/310223/110552648-9081e080-80ec-11eb-8d21-5ba06c9fc2a3.png">

The user should be redirected to their private slate, instead they are redirected to:

<img width="1480" alt="Screen Shot 2021-03-09 at 3 27 03 PM" src="https://user-images.githubusercontent.com/310223/110552673-9d063900-80ec-11eb-8c40-50b616e4b337.png">

The obvious action from here would be to hard fresh, here is what happens:

<img width="1480" alt="Screen Shot 2021-03-09 at 3 32 27 PM" src="https://user-images.githubusercontent.com/310223/110552728-aee7dc00-80ec-11eb-8851-1e63eab5d1e6.png">

This case makes sense because there is no identifier for the Slate, still, its the incorrect behavior since the user should be taken to their private slate on hard fresh.

**Comment by martinalong** [comment]
Fixed. Was a small typo causing any private slates that were fetched (rather than linked to through your slates page) to register as "access denied"
