### ISSUE TITLE
feature request: import existing IPFS files

### ISSUE THREAD

**Issue by bam80** [filecoin-project/slate#634]
Currently, files added to Slate are happen to be on IPFS.
Is opposite direction possible? I had some images on IPFS before, can I view them via Slate without re-uploading?

**Comment by jimmylee** [comment]
Files are only on IPFS or cached through an IPFS gateway. Slate does not have any files on its own servers.

**Comment by bam80** [comment]
> Files are only on IPFS or cached through an IPFS gateway. Slate does not have any files on its own servers.

That's what I understand.
But how existing files that was put on IPFS before could be seen in Slate? I don't know any other way than re-import them via Slate Web interface.
