### ISSUE TITLE
Expose user bucket CID on the API page

### ISSUE THREAD

**Issue by bam80** [filecoin-project/slate#635]
So I could for example mount my gallery with FUSE and view it locally.

**Comment by jimmylee** [comment]
You should be able to, Every bucket has a CID you can view through an IPFS gateway, we just have to expose it. (cc: @martinalong)

**Comment by martinalong** [comment]
Yeah we can do this. Keep in mind that it won't be organized in slates however. It'll basically be like your data page—just all the files you have stored on slate

I'll put it on the road map to expose the root bucket cid somewhere on the API page
