### ISSUE TITLE
Product: KPIS / Performance

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#64]
![cube_shadow-1](https://user-images.githubusercontent.com/310223/87359832-8daefb80-c51d-11ea-923d-ce2ad9ae4c40.jpg)

# Introduction

We'd like to measure **Slate's** performance at launch. 

In addition we would like to share with the public what indicators we are measuring so our audience can understand how we view success internally. If there are differences between how we view success, we can work hard to close that gap of understanding together as a community.

This topic is likely to expand as we get more tactical around adoption pain points.

### Timeline

* Targeting official launch in September 14th.
* Product should be usable before this date and instrumented. (No official timeline other than weekly product goals to maintain fluidity).

### Terminology

* **User**: Any actor in the system who has created a username.
* **Active user**: Any **user** who participates in the meaningful flows of the application.

### Meaningful Active Users / Monthly Active Users (MAU)

* I've selected MAU as the Q3 2020/Q4 2020/Q1 2021 focus instead of WAU, DAU or PCU.
* Focused on getting **100 MAU** around official launch time as a baseline.
* Focused on long term reaching 30,000 MAU.
  * We will restructure our goals accordingly to get here based on post launch learnings.
* Users in the aggregate cohort have completed the following behaviors:
  * Claimed a username (Account creation)
  * Created a bucket
  * Created a board
  * Logged in
  * Stored data
* Users that still qualify in the aggregate cohort 
  * Log in to user account.
  * View buckets
* Interesting topics
  * API usage + versus returning to the GUI.
  * Filecoin transactions per user
  * Filecoin transaction size per user

### Active User Retention Rate (Start)

* **7** day retention cohort (Expectation: 40%)
* **14** day retention cohort (Expectation: 25%)
* **21** day retention cohort (Expectation: 15%)
* Useful for catching bottlenecks such as:
  * Why a user hasn't created a bucket?
  * Why hasn't a new user created a username?
  * Why hasn't a user stored any data?

### Monthly Data Uploaded to Textile Services/Filecoin

* Total data size uploaded by all users.
* Total data retrieved by all users.
* Total number of users retrieving data.
* Total number of users storing data.
* Total number of public views of data (Buckets).
* TBD: We will aim for some **meaningful percentage of the total size of data** on the Filecoin Network.
* TBD: Find out comparisons from other meaningful products.

### Downloads

+ Total number of downloads from marketing sites.
+ Total number of downloads.
+ Total number of unique referrers.

**Comment by prastut** [comment]
Hi Jimmy, coming from your recent presentation on "How we built Slate". 

Super fantastic work and my the UI is gorgeous! Breath of fresh air :D

I was just scanning around the repo and saw this thread, and being a data geek was curious if and where are you tracking these KPI's.

**Comment by jimmylee** [comment]
Hey prastut! Welcome the party :)

We're tracking this in our database at the moment. I don't expose these numbers publicly but the database is a postgres database :)
