### ISSUE TITLE
Increasing storage to 30GB

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#647]
Remove the slate limit on 4GB. Textile already suports 32 GB

Test it out before announcing it

**Comment by jimmylee** [comment]
You should revise this title to 32 GB unless 30 is intentional?

**Comment by martinalong** [comment]
30 is intentional. Andrew mentioned that it may not be exactly 32 for various reasons, so we decided to do a clean 30 GB

**Comment by jimmylee** [comment]
Got it sounds good, it seems like they'll probably play with padding before the Filecoin storage deal is made.
