### ISSUE TITLE
Possibly unnecessary step included in README for running local devnet

### ISSUE THREAD

**Issue by ltfschoen** [filecoin-project/slate#66]
# Purpose

In this section "Setup Lotus DevNet and Powergate" Slate docs https://github.com/filecoin-project/slate#setup-lotus-devnet-and-powergate, why do we need to do these first two steps?

> Clone the Lotus DevNet repository.
> Run `docker run -e TEXLOTUSDEVNET_SPEED=1500 textile/lotus-devnet`

If I only followed the following last couple of steps I'm still able to use Slate to generate a new Powergate token and create a new Powergate token (by creating the app that was described in this "Building an App with Filecoin from scratch - using Slate Components & Powergate" YouTube video https://www.youtube.com/watch?v=FJjPMKRy8xQ.
I believe this is the case because it also creates a Lotus Devnet container https://github.com/textileio/powergate/blob/master/docker/docker-compose-localnet.yaml#L26

> Clone Powergate.
> Follow the instructions and run the commands in the README.md file:
> Run `cd docker; make localnet`

# Deliverable

*Tell us about what the outcome of resolving this issue will be*

# Dependencies

N/A

**Comment by jimmylee** [comment]
@ltfschoen if this is the case, you've saved me a lot of grief :) Thank you! I'll look into this today.

**Comment by jimmylee** [comment]
Thanks to Textile we now have a hosted Powergate instance :)
