### ISSUE TITLE
my upload do not show any preview

### ISSUE THREAD

**Issue by lucasespinosa28** [filecoin-project/slate#672]
I tried to upload a WebGL Unity game and an html both files did not work

![Captura de Tela (2)](https://user-images.githubusercontent.com/52639395/112772013-e4555a80-9004-11eb-9b33-e9f9646d9cc9.png)

**Comment by jimmylee** [comment]
Assigning @Aminejvm and @akuokojnr who worked on this

**Comment by akuokojnr** [comment]
@lucasespinosa28 I am happy to assist here. 

You do not need an html file to be able to preview Unity WebGL games in Slate. To help better resolve the issue you are facing, can you kindly answer the following:
1. Did you upload a zip of the build folder of the Unity WebGL game?
2. What is the directory structure of the Unity WebGL game build folder?

**Comment by lucasespinosa28** [comment]
I did upload a zip with the build folder and another with archives in the build folder. both show no preview
### the entire folder
![Captura de Tela (11)](https://user-images.githubusercontent.com/52639395/112848220-38e8ec00-907e-11eb-807b-ec6dec2cae0c.png)

### the build folder
![Captura de Tela (12)](https://user-images.githubusercontent.com/52639395/112848251-400ffa00-907e-11eb-8817-09fce3b52336.png)

 my unity version is 2020.2.7f1

**Comment by jimmylee** [comment]
After @akuokojnr's fix is there still a problem? trouble https://github.com/slate-engineering/shovel/pull/9

**Comment by akuokojnr** [comment]
Thanks for sharing these @lucasespinosa28 I have fixed the issue. Can you try and upload the game again and see if it works for you?

**Comment by lucasespinosa28** [comment]
the problem was fixed, thanks
