### ISSUE TITLE
QA: Slate Extension V2 Final Testing

### ISSUE THREAD

**Issue by jasonleyser** [filecoin-project/slate#708]
Help us test all features of the Chrome Extension before the public release, scheduled for Friday, April 23rd!

To test, clone and install locally from:
[https://github.com/slate-engineering/slate-for-chrome](https://github.com/slate-engineering/slate-for-chrome)

*If you already have the Chrome Extension V2 installed locally, you need to pull the repo and update the extension under the `Manage Extensions` page. 

**Settings**
→ Add an API key (or multiple) on the Welcome page and/or the Settings page
→ Change your `Primary key` for direct uploads - Your primary key will always be the first API key

**Uploads**
→ Click the Slate icon to test mass uploading
→ Try the shortcut `cmd+shift+S`

* this should open the main Slate app
→ Right click on a image, click `Upload to a slate` to test a single image upload
→ Right click on a image, click `Direct upload` to test the direct uploads (It should automatically upload to your Primary key)

→ After uploading, close the app and allow the uploads to run in the background while you continue to browse
→ After uploading, leave the app open to test the `Upload progress` UI updates as the files successfully upload 
→ After uploading, close the app and reopen it to test the blue upload alert bar updates as the files successfully upload 

**Upload history**
→ Clicking the source URL should open that webpage in a separate tab
→ Click the 3 dots and the `View file on Slate`, to test the `https://slate.textile.io/ipfs/` link
→ Click the `Clear history` button to test clearing your local storage

TODO (jason):

* [x] fix the typography in public domain and internet archive product tour
* [ ] "pin the extension" module
* [x] checkbox & image placement
* [x] center align slate name text
* [x] upload history margin
* [x] date format
* [x] add links to direct file in slate after an upload

**Comment by tarafanlin** [comment]
### Bug
→ when testing unsplash, it doesn't seem to scrap all the images I see on the page 

### Design QA
→ fix the typography in public domain and internet archive product tour, to be consistent with the one for unsplash
→ add a line in the second tour module, says something about "pin the extension" in your tab bar
→ this checkbox is a bit off, image should scale down a little towards the center, not towards the right
<img width="291" alt="Screen Shot 2021-04-14 at 10 50 31 AM" src="https://user-images.githubusercontent.com/35607644/114756113-42758380-9d0f-11eb-8e71-7ebf549c22ad.png">
→ do we still allow for configuring the upload history? if not, we don't need this in settings page
<img width="1413" alt="Screen Shot 2021-04-14 at 10 51 57 AM" src="https://user-images.githubusercontent.com/35607644/114756298-70f35e80-9d0f-11eb-80c3-59608b74a3f1.png">
→ center align this horizontally
<img width="450" alt="Screen Shot 2021-04-14 at 10 54 07 AM" src="https://user-images.githubusercontent.com/35607644/114756573-bf086200-9d0f-11eb-824b-1037604d21a6.png">
→ the page margin here doesn't seem right, the button go out the the container. And we could use a better empty state design
<img width="1792" alt="Screen Shot 2021-04-14 at 10 55 08 AM" src="https://user-images.githubusercontent.com/35607644/114756709-e3fcd500-9d0f-11eb-8656-31905d63e54f.png">
→ date uploaded & source too close
<img width="1127" alt="Screen Shot 2021-04-14 at 10 59 01 AM" src="https://user-images.githubusercontent.com/35607644/114757220-6f766600-9d10-11eb-8af8-398693ad9bcf.png">
→ this language is a little confusing, do you mean "cancel upload" or something?
<img width="252" alt="Screen Shot 2021-04-14 at 11 03 36 AM" src="https://user-images.githubusercontent.com/35607644/114757746-122ee480-9d11-11eb-91fd-59d7ef014698.png">


### Feature
→ would be great if there is some cid/link here when upload finishes so you could view in on Slate
<img width="464" alt="Screen Shot 2021-04-14 at 10 56 49 AM" src="https://user-images.githubusercontent.com/35607644/114756956-20303580-9d10-11eb-8d10-80472fd6f581.png">
→ I think we should take people to view the file carousel with sidebar on Slate, not the raw file on textile.
<img width="481" alt="Screen Shot 2021-04-14 at 10 59 51 AM" src="https://user-images.githubusercontent.com/35607644/114757316-8c129e00-9d10-11eb-9059-73b7fe8e8531.png">

**Comment by tarafanlin** [comment]
can the extension assign a placeholder title to files with no title? currently it's impossible to edit filename if there isn't one from the beginning.
<img width="1792" alt="Screen Shot 2021-04-15 at 1 18 52 PM" src="https://user-images.githubusercontent.com/35607644/114933208-48419680-9ded-11eb-9ace-63891ab70734.png">

**Comment by jasonleyser** [comment]
@tarafanlin oh interesting, it should have a default title if one wasn't provided. Do you remember which way you uploaded this? (as in through the slate icon, right click, etc)

**Comment by tarafanlin** [comment]
> @tarafanlin oh interesting, it should have a default title if one wasn't provided. Do you remember which way you uploaded this? (as in through the slate icon, right click, etc)

i use right click -> upload to a slate
