### ISSUE TITLE
ffs: Unable to store string to Lotus testnet using PowerGate FFS

### ISSUE THREAD

**Issue by ltfschoen** [filecoin-project/slate#71]
# Purpose

I've tried to implement a modified approach to using Slate's "Make a Storage Deal" code, where my objective is to simply store an actual IPFS Hash (instead of a File) to the Lotus Filecoin Testnet using PowerGate FFS. Note that the IPFS Hash represents the latest Pin where the frontend of my website is stored, which I've done using Pinata SDK.

Please see the description in this PR https://github.com/ltfschoen/ethquad/pull/7, which includes screenshots, and a list of issues I've encountered, and the list of steps you could follow to replicate the issues.

Note: This is a duplicate of https://github.com/textileio/powergate/issues/521, because I know @jimmylee maintains this repo, and did some live coding about Slate's "Make a Storage Deal"

# Deliverable

I'll be able to store a string on the Lotus testnet using PowerGate FFS and know how to detect when it's finally been stored.
I'll know how to make queries without having to use try/catch blocks so it doesn't crash when I call an FFS function.

**Comment by jimmylee** [comment]
Looks like @asutula has addressed your issue, but if not, here is my take at it:

```js
// You can either pass a Uint8Array
const { cid } = await this.PG.ffs.addToHot(arrayStructure);

// Or you can pass in a cid (string)
const { jobId } = await this.PG.ffs.pushConfig(cid);
```

For simplicity sake, Slate won't be supporting other cases (Unless Textile's Buckets require it). Hope that helps. Feel free to re-open if this doesn't answer your question :) Happy hacking!
