### ISSUE TITLE
homescreen bookmark from Safari iOS has no icon

### ISSUE THREAD

**Issue by autonome** [filecoin-project/slate#711]
# Purpose

STR:

1. open Safari on iOS
2. log in to slate.host
3. click the share button and choose "Add to Home Screen"

# Deliverable

Expected: Item on homescreen is the Slate logo, sizzling hot and eminently clickable

Actual: Item on homescreen looks like OS default when there's no logo - a screenshot of the page, turned micro

Screenshot:

![IMG_5164](https://user-images.githubusercontent.com/50103/114964331-80bc9100-9e3c-11eb-8063-deee0eb8a234.jpg)

**Comment by autonome** [comment]
Also, the default title wasn't great - "Slate : Welcome back!". Just defaulting to Slate is probably fine, but maybe that's for another issue to discuss.

**Comment by autonome** [comment]
To clarify - wasn't great only because I had to edit it manually not just use the default for this use-case.

**Comment by akuokojnr** [comment]
Fixed by #728
