### ISSUE TITLE
alt text should show full title in gallery view

### ISSUE THREAD

**Issue by autonome** [filecoin-project/slate#712]
# Purpose
Many files uploaded have titles that provide meaningful user action only if you know file type.

However, Slate truncates. In the screenshot below, these are all PDFs, but you'd have to click on them to know that:

![](https://user-images.githubusercontent.com/50103/114964752-515a5400-9e3d-11eb-9544-494790a04a3f.png)

One solution is alt text with full name.

Other way could be MIME type sniffing, storing that w/ file metadata and then showing file type clearly w/ icon or text.

Those are not mutually exclusive solutions. Likely there are more side benefits of being able to access the full title without clicking on an item.

# Deliverable
Either of above solutions, and preferably both.

# Dependencies
I depend on air, water and the open web.

**Comment by martinalong** [comment]
I'm guessing this screenshot is from the activity or explore page? So we currently have the file ending (PDF, TXT, etc) below the title everywhere else, but went with this format (the slate that the file belongs to) just for activity/explore. 

This should be resolved in our next iteration of activity/explore soon

**Comment by autonome** [comment]
ah yes, explore page! feel free to close if already fixed!

**Comment by martinalong** [comment]
Not fixed yet but look out for a major update to explore/activity sometime soon! And we'll make sure this is included

**Comment by martinalong** [comment]
![image](https://user-images.githubusercontent.com/33686587/119238774-84a59800-baf9-11eb-86b3-0dbcb570b46a.png)

![image](https://user-images.githubusercontent.com/33686587/119238783-95560e00-baf9-11eb-9b4b-24e0ce87bf1e.png)

Just an intermediary update! The new design for objects will include a more clear type tag, and we'll eventually add specific visual language for common file types (e.g. a play button for videos, a folded corner for documents). We are projected to get started on implementing it this coming week

**Comment by autonome** [comment]
Ohhhh looks amazing 🤩
