### ISSUE TITLE
DUPLICATE_FILE error should return file data

### ISSUE THREAD

**Issue by vikiival** [filecoin-project/slate#734]
# Purpose

In [KodaDot](https://github.com) we would like to expolore and integrate the Slate app.
However, when I try to reupload the same image I'll get  HTTP status `400`.

<img width="1552" alt="Screenshot 2021-04-27 at 21 58 03" src="https://user-images.githubusercontent.com/22471030/116305263-cfa2e880-a7a3-11eb-8eb3-d5a529522e87.png">

# Deliverable

I would expect that response should return the same data as HTTP status `200`
e.g response should contain `data` with `id` and `cid`

# Dependencies

N/A

## Optiona
I would use HTTP status `302` for duplicated file

https://http.cat/302

**Comment by martinalong** [comment]
https://github.com/slate-engineering/shovel/pull/14

Fixed to send back a 200 status with the file regardless of whether it is a duplicate or not! Let me know if that is working for you

And let us know if there's anything else we can do to help or any features you'd like to see!

**Comment by vikiival** [comment]
Yeah, it works.

Love it ❤️
