### ISSUE TITLE
Objects view 2.0

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#743]
## Purpose
rethink objects gallery and table view page to make organize and search more intuitive
currently table view is not responsive

## Design
tbd

**Comment by mrtngrsbch** [comment]
Hi all,

Sorry I can't help with the code for this project, but I would like to suggest an important feature for GLAM collections (galleries, libraries, archives and museums).

It would be very interesting to be able to extract the metadata from an image and present it together with the description. The best library, no doubt, is: https://exiftool.org/

I am a contributor to [jExifToolGUI](https://github.com/hvdwolf/jExifToolGUI) and our latest developments have gone in that direction at the request of the community.

best

**Comment by mrtngrsbch** [comment]
Forgive me for returning to the subject, but I would like to give you some more valuable information for archives and museums, which will undoubtedly be an excellent promoter.
The GLAM universe uses a set of metadata standards that are not supported by most image editors and viewers. 
It is for this reason that a group of interested parties have undertaken some improvements in reading and editing metadata, based on [jExifToolGUI](https://github.com/hvdwolf/jExifToolGUI) and [ExifTool](https://exiftool.org/).

This enhancement is composed of the extension of the traditional XMP metadata set and we are currently working on [VRA Core](https://www.loc.gov/standards/vracore/) and [ISAD(G)](https://www.ica.org/en/isadg-general-international-standard-archival-description-second-edition).

Traditionally, in the vast majority of archives and museums, image metadata is stored in a separate CSV, so our strategy is based on incorporating this metadata into the images.

You can see an example in this image
![vrae_exiftool_example](https://user-images.githubusercontent.com/693328/123314020-7683d680-d500-11eb-8815-6d16ba3274eb.jpg)
`# exiftool -xmp:all -a vrae_exiftool_example.jpg
`

I am currently uploading collections to: https://slate.host/museosabiertos to start looking into the possibility of creating an Open Content Repository in IPFS.

I am available for any help I can give

best
