### ISSUE TITLE
Profile 3.0

### ISSUE THREAD

**Issue by tarafanlin** [filecoin-project/slate#744]
## Purpose
Profile has some visual updates to be made

## Design
https://www.figma.com/file/0voxrNz1nlhkrdjwsSKyGd/Profile-3.0?node-id=0%3A1

┆Issue is synchronized with this [Notion page](https://www.notion.so/Profile-3-0-00b00ce93da340e9a2c7b1c502e0a371) by [Unito](https://www.unito.io)

**Comment by mrtngrsbch** [comment]
Hi,
is the link to the design broken or is it for internal use?
