### ISSUE TITLE
Username underscore bug

### ISSUE THREAD

**Issue by jasonleyser** [filecoin-project/slate#796]
# Purpose
There's a bug where you can add an underscore to your existing username in profile settings, but on the main login screen an underscore is automatically changed to a dash, meaning you won't be able to log back in after.

# Deliverable
Either allow underscores in main login or disable the ability to add underscores in profile settings.

**Comment by chrisijoyah** [comment]
@jasonleyser was interested in picking this one up but it looks like it might have already been resolved. The login ui on the `main` branch looks like it's been updated and I am able type both underscores and hyphens inside the username field, something that is not currently possible in the live version. Slate seems like a great use case for IPFS and would like to get involved any way I can.

**Comment by martinalong** [comment]
I put in a modification to the username regex which was incorporated by @Aminejvm as a part of the new auth. So this issue should be fixed on main. (Just haven't closed the issue since it hasn't landed in production yet)

**Comment by martinalong** [comment]
> @jasonleyser was interested in picking this one up but it looks like it might have already been resolved. The login ui on the `main` branch looks like it's been updated and I am able type both underscores and hyphens inside the username field, something that is not currently possible in the live version. Slate seems like a great use case for IPFS and would like to get involved any way I can.

@chrisijoyah would love to have you involved! Shoot me an email at martina@slate.host and we can continue there
