### ISSUE TITLE
Design: Update the design system layout to increase readability

### ISSUE THREAD

**Issue by gndclouds** [filecoin-project/slate#87]
# Purpose

To encourage adoption and ease of use we can look into updating the structure of the current Design System and Documentation site.

# Deliverable

Update the layout of how the input and output section is displayed and possibly make elements editable as a stretch goal. Some examples we can look to for reference might be [Stripe Docs](https://stripe.com/docs/api) or [Particle's docs](https://docs.particle.io/reference/device-os/firmware/boron/).

Some of what this might look like:

General Updates:
- Dark mode
- Display input and output side by side.

Codeblocks Updates
- Make them interactive see [Stripe Example](https://stripe.com/docs/payments/integration-builder)
- Copy codeblock to clipboard via icon.

# Dependencies

- #77

**Comment by gndclouds** [comment]
Progress is being made! Currently focusing on #77 since the designs will influence this issue. :-)

**Comment by jimmylee** [comment]
Awesome!

**Comment by tarafanlin** [comment]
**Might be helpful**
Atomize component doc: https://atomizecode.com/docs/react/atoms
