### ISSUE TITLE
NPM module for components

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#9]
# Purpose

`npm install whatever-we-call-our-system`

# Deliverable

+ `import { Component } from whatever-we-call-our-system`
+ `import AllComponents from whatever-we-call-our-system`
+ `import { Constants } from whatever-we-call-our-system`
+ One link to point people to
+ Github `README.md` instructions

# Dependencies

+ https://github.com/filecoin-project/filecoin-client/issues/7

**Comment by jimmylee** [comment]
This is still blocked on me but I've directed @achalvs to https://medium.com/better-programming/lets-build-react-components-library-part-3-b2e7aec478a2

Once this is done, @vasa-develop you will be able to npm install the components bundle :)

**Comment by vasa-develop** [comment]
Awesome 👍 Thanks for this @jimmylee

**Comment by jimmylee** [comment]
`npm install --save slate-react-system` works now, but I need to add some more redundant styling.
