### ISSUE TITLE
Feature: Define a format for users to paste requisite info to retrieve files.

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/slate#91]
# Purpose
Through Filecoin Discover, we will be storing tons of open source data. In the process of doing this, we'll be storing all the requisite information for retrieval. For our users, we'd like them to be able to navigate our UI and copy out the relevant info for retrieval, and have a place for them to paste it to get the data back. Since some of these files can be quite large, we don't want this to be hosted (necessarily) on our UI. 

Based on the information in our UI, we can generate a JSON blob that can contain the requisite information for retrieval - we can format this in any way thats most useful (and perhaps consistent with other retrieval things?) but the high level ask is for us to coordinate the structure that we can implement on our side, to drop in for retrieval!
# Deliverable

Together it would be great to scope: 
1) How retrieval for files stored external to Slate works
2) Define a structure of a command (or JSON blob) that Slate can accept for retrieval
3) Use Slate as the default retrieval flow for users trying to pull data out of Filecoin Discover!

# Dependencies

N/A

**Comment by jnthnvctr** [comment]
@harisbutt for tracking

**Comment by ribasushi** [comment]
Hi, I'm the person tasked with designing/implementing this on the lotus side. The implementation of this is scheduled to take place in the next ~5 days or so, pending lotus retrieval-module fixes.

If you would like to meet for 15 minutes to arrive on a spec synchronously would be happy to do that. Alternatively point me to some doc/source on what you have built so far, so I can propose a point of convergence here.

Thanks!

**Comment by jimmylee** [comment]
@ribasushi yes would be great to schedule some time to talk, this week or the next!

@jnthnvctr 

1. **High level**: We use Textile's Buckets or Powergate's Filecoin Cold storage right now at the moment.
2. We can take any structure, maybe it makes sense to return an index such as:

```json
{
  "type:": "some-type-some-thing",
  "data": [ "path-1", "path-2", "path-3" ]
}
```

In case we need to break up extremely large files.

3. Slate will have an API key for each user account. So there should be away to do something programmatically between Slate and Discover UI.
4. We can also provide an authentication API (log in with Slate). This could allow retrieval directly into the Slate Textile Bucket each user has.

**Comment by jimmylee** [comment]
<img width="1725" alt="Screen Shot 2020-07-28 at 5 06 28 PM" src="https://user-images.githubusercontent.com/310223/88830679-23d05c00-d183-11ea-8d85-ac39a725f979.png">

* I'll be able to start looking at the details of our integration now that this exists.
* Either through CURL or JavaScript it would be interesting to see the shape of the data that is coming from Discovery UI (cc: @ribasushi), I'll make sure to support that case and adjust the product as necessary.

**Comment by jimmylee** [comment]
For tracking:

* https://github.com/ipfs/js-ipfs/pull/2953/files
* Agreement with @ribasushi that Slate's responsibility is `.car` unpacking and contents retrieval.

**Comment by ribasushi** [comment]
> Agreement with @ribasushi that Slate's responsibility is .car unpacking

We need to circle back to that tomorrow - I am actually not sure whether this is workable. More likely the request for "part of .car" needs to be proxied to Powergate. We'll iterate in the doc @jnthnvctr is putting together.

**Comment by jimmylee** [comment]
We're tracking this issue elsewhere so I'll close this for now.
